// Package ddl reads the table definitions of a live database and writes them
// as DDL that detest's simulated database accepts: tables, column defaults, primary keys,
// unique constraints and unique indexes. Run it against the database a
// project's integration tests already use, then execute the result on the
// handle detest.Sim.DB returns.
package ddl

import (
	"context"
	"database/sql"
	"fmt"
	"slices"
	"strings"

	"github.com/k1LoW/detest"
	"github.com/k1LoW/detest/internal/sqlir"
)

// Option narrows what From reads.
type Option func(*config)

type config struct {
	schemas []string
	tables  []string
}

// Schemas reads the tables of these schemas. The default is the database's
// search path (Postgres) or the current database (MySQL).
func Schemas(names ...string) Option { return func(c *config) { c.schemas = names } }

// Tables reads only these tables, each as written in queries: unqualified, or
// schema-qualified for a table outside the default schemas.
func Tables(names ...string) Option { return func(c *config) { c.tables = names } }

// From reads db's table definitions and returns them as DDL for a server of
// kind s, such as postgres.New().
func From(ctx context.Context, db *sql.DB, s detest.Server, opts ...Option) (string, error) {
	c := &config{}
	for _, o := range opts {
		o(c)
	}
	kind := sqlir.ImplOf(s)
	if kind == nil {
		return "", fmt.Errorf("ddl: From needs a server, such as postgres.New()")
	}
	switch kind.Name() {
	case "postgres":
		return fromPostgres(ctx, db, c)
	case "mysql":
		return fromMySQL(ctx, db, c)
	}
	return "", fmt.Errorf("ddl: server %s is not supported", kind.Name())
}

func (c *config) wants(schema, table string, defaultSchema bool) bool {
	if len(c.tables) == 0 {
		return true
	}
	return slices.Contains(c.tables, schema+"."+table) || (defaultSchema && slices.Contains(c.tables, table))
}

func fromPostgres(ctx context.Context, db *sql.DB, c *config) (string, error) {
	schemas := c.schemas
	if len(schemas) == 0 {
		rows, err := db.QueryContext(ctx, `SELECT unnest(current_schemas(false))`)
		if err != nil {
			return "", err
		}
		for rows.Next() {
			var s string
			if err := rows.Scan(&s); err != nil {
				rows.Close()
				return "", err
			}
			schemas = append(schemas, s)
		}
		rows.Close()
		if err := rows.Err(); err != nil {
			return "", err
		}
	}
	type table struct {
		oid            int64
		schema, name   string
		defaultSchema  bool
		qualifiedIdent string
	}
	var tables []table
	for i, schema := range schemas {
		rows, err := db.QueryContext(ctx, `
SELECT c.oid, c.relname, quote_ident(n.nspname) || '.' || quote_ident(c.relname)
FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
WHERE c.relkind IN ('r', 'p') AND n.nspname = $1 AND NOT c.relispartition
ORDER BY c.relname`, schema)
		if err != nil {
			return "", err
		}
		for rows.Next() {
			t := table{schema: schema, defaultSchema: i == 0 && len(c.schemas) == 0}
			if err := rows.Scan(&t.oid, &t.name, &t.qualifiedIdent); err != nil {
				rows.Close()
				return "", err
			}
			if c.wants(t.schema, t.name, t.defaultSchema) {
				tables = append(tables, t)
			}
		}
		rows.Close()
		if err := rows.Err(); err != nil {
			return "", err
		}
	}
	var b strings.Builder
	for _, t := range tables {
		var defs []string
		cols, err := db.QueryContext(ctx, `
SELECT quote_ident(a.attname), format_type(a.atttypid, a.atttypmod),
       coalesce(pg_get_expr(d.adbin, d.adrelid), ''), a.attidentity, a.attgenerated, a.attnotnull,
       CASE WHEN a.attcollation <> 0 AND a.attcollation <> ty.typcollation
            THEN quote_ident(cn.nspname) || '.' || quote_ident(co.collname) ELSE '' END
FROM pg_attribute a
JOIN pg_type ty ON ty.oid = a.atttypid
LEFT JOIN pg_collation co ON co.oid = a.attcollation
LEFT JOIN pg_namespace cn ON cn.oid = co.collnamespace
LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
WHERE a.attrelid = $1 AND a.attnum > 0 AND NOT a.attisdropped
ORDER BY a.attnum`, t.oid)
		if err != nil {
			return "", err
		}
		for cols.Next() {
			var name, typ, def, identity, generated, collation string
			var notNull bool
			if err := cols.Scan(&name, &typ, &def, &identity, &generated, &notNull, &collation); err != nil {
				cols.Close()
				return "", err
			}
			col := name + " " + typ
			if collation != "" {
				// A collation of the column's own orders its text instead of
				// the database's, which detest has to know to order it.
				col += " COLLATE " + collation
			}
			switch {
			case identity == "a":
				col += " GENERATED ALWAYS AS IDENTITY"
			case identity == "d":
				col += " GENERATED BY DEFAULT AS IDENTITY"
			case generated == "s", generated == "v":
				// A virtual column (the default since Postgres 18) is written
				// as STORED: the grammar detest parses with has no VIRTUAL,
				// and detest computes the value on every write either way.
				col += " GENERATED ALWAYS AS (" + def + ") STORED"
			case def != "":
				col += " DEFAULT " + def
			}
			if notNull {
				col += " NOT NULL"
			}
			defs = append(defs, col)
		}
		cols.Close()
		if err := cols.Err(); err != nil {
			return "", err
		}
		cons, err := db.QueryContext(ctx, `
SELECT quote_ident(conname), pg_get_constraintdef(oid)
FROM pg_constraint WHERE conrelid = $1 AND contype IN ('p', 'u')
ORDER BY contype, conname`, t.oid)
		if err != nil {
			return "", err
		}
		for cons.Next() {
			var name, def string
			if err := cons.Scan(&name, &def); err != nil {
				cons.Close()
				return "", err
			}
			defs = append(defs, "CONSTRAINT "+name+" "+def)
		}
		cons.Close()
		if err := cons.Err(); err != nil {
			return "", err
		}
		fmt.Fprintf(&b, "CREATE TABLE %s (\n    %s\n);\n", t.qualifiedIdent, strings.Join(defs, ",\n    "))
		// Unique indexes that do not back a constraint written above.
		idx, err := db.QueryContext(ctx, `
SELECT pg_get_indexdef(i.indexrelid)
FROM pg_index i JOIN pg_class ic ON ic.oid = i.indexrelid
WHERE i.indrelid = $1 AND i.indisunique
  AND NOT EXISTS (SELECT 1 FROM pg_constraint c WHERE c.conindid = i.indexrelid)
ORDER BY ic.relname`, t.oid)
		if err != nil {
			return "", err
		}
		for idx.Next() {
			var def string
			if err := idx.Scan(&def); err != nil {
				idx.Close()
				return "", err
			}
			b.WriteString(def + ";\n")
		}
		idx.Close()
		if err := idx.Err(); err != nil {
			return "", err
		}
	}
	return b.String(), nil
}

func fromMySQL(ctx context.Context, db *sql.DB, c *config) (string, error) {
	schemas := c.schemas
	if len(schemas) == 0 {
		var current sql.NullString
		if err := db.QueryRowContext(ctx, `SELECT DATABASE()`).Scan(&current); err != nil {
			return "", err
		}
		if !current.Valid {
			return "", fmt.Errorf("ddl: no current database; pass Schemas")
		}
		schemas = []string{current.String}
	}
	var b strings.Builder
	for i, schema := range schemas {
		rows, err := db.QueryContext(ctx, `
SELECT table_name FROM information_schema.tables
WHERE table_schema = ? AND table_type = 'BASE TABLE' ORDER BY table_name`, schema)
		if err != nil {
			return "", err
		}
		var names []string
		for rows.Next() {
			var n string
			if err := rows.Scan(&n); err != nil {
				rows.Close()
				return "", err
			}
			if c.wants(schema, n, i == 0 && len(c.schemas) == 0) {
				names = append(names, n)
			}
		}
		rows.Close()
		if err := rows.Err(); err != nil {
			return "", err
		}
		for _, n := range names {
			var table, create string
			q := fmt.Sprintf("SHOW CREATE TABLE `%s`.`%s`", strings.ReplaceAll(schema, "`", "``"), strings.ReplaceAll(n, "`", "``"))
			if err := db.QueryRowContext(ctx, q).Scan(&table, &create); err != nil {
				return "", err
			}
			b.WriteString(create + ";\n")
		}
	}
	return b.String(), nil
}
