package postgres_test

import (
	"testing"

	"github.com/k1LoW/detest/internal/difftest"
)

// The values cases compare how detest converts and compares values with
// Postgres: untyped literals, values written to typed columns, row
// comparisons, IN with NULLs, large integers, numeric arithmetic and casts,
// column length and scale limits, NULL semantics, ordering and booleans.
// A query returns ids, counts and booleans rather than numerics, whose digits
// as written detest does not keep (README).
var (
	valueSchema = []string{`CREATE TABLE t (id int PRIMARY KEY, ratio float8, amount numeric, name text)`}
	valueSeed   = []string{
		`INSERT INTO t VALUES ('1', '0.5', '99.00', 'a')`,
		`INSERT INTO t VALUES (2, 1.5, 100.50, '2')`,
		`INSERT INTO t VALUES (9, 2, 7, NULL)`,
		`INSERT INTO t VALUES (10, NULL, 1.5, 'x')`,
	}
)

var valueCases = []difftest.Case{
	{
		Name:   "untyped literal compared with a number",
		Schema: valueSchema, Seed: valueSeed, Conns: 1,
		Steps: []difftest.Step{
			difftest.Q(0, `SELECT id FROM t WHERE id = '01'`),
			difftest.Q(0, `SELECT id FROM t WHERE id IN ('01', '2') ORDER BY id`),
			difftest.Q(0, `SELECT id FROM t WHERE id < '10' ORDER BY id`),
			difftest.Q(0, `SELECT id FROM t WHERE id = ANY (ARRAY[9, '10']) ORDER BY id`),
			difftest.Q(0, `SELECT id FROM t WHERE name = ANY (ARRAY['2', 'x']) ORDER BY id`),
			difftest.Q(0, `SELECT id FROM t WHERE name = ANY (ARRAY['2', NULL::text]) ORDER BY id`),
			difftest.Q(0, `SELECT id FROM t WHERE name = ANY (ARRAY[NULL]) ORDER BY id`),
			difftest.Q(0, `SELECT CASE id WHEN '09' THEN 'nine' ELSE 'other' END FROM t ORDER BY id`),
			difftest.Q(0, `SELECT id FROM t WHERE NULLIF(id, '01') IS NULL`),
			difftest.Q(0, `SELECT count(*) FROM t HAVING count(*) = '04'`),
			difftest.Q(0, `SELECT id FROM t WHERE '01' IN (SELECT id FROM t) ORDER BY id`),
			difftest.Q(0, `SELECT id FROM t WHERE name = '2'`),
			difftest.Q(0, `SELECT count(*) FROM t WHERE id = 'abc'`),
		},
	},
	{
		Name:   "values written to typed columns",
		Schema: valueSchema, Seed: valueSeed, Conns: 1,
		Steps: []difftest.Step{
			difftest.Q(0, `SELECT id FROM t WHERE amount < 100 ORDER BY id`),
			difftest.Q(0, `SELECT id FROM t ORDER BY amount, id`),
			difftest.Q(0, `SELECT id FROM t WHERE ratio > 1 ORDER BY id`),
			difftest.S(0, `INSERT INTO t (id) VALUES ('01')`),
			difftest.S(0, `INSERT INTO t (id) VALUES ('abc')`),
			difftest.S(0, `INSERT INTO t (id) VALUES ('1.5')`),
			difftest.S(0, `INSERT INTO t (id, amount) VALUES (5, 'abc')`),
			difftest.S(0, `INSERT INTO t (id) VALUES ('9223372036854775808')`),
			difftest.S(0, `INSERT INTO t (id, ratio) VALUES (7, '1e400')`),
			difftest.S(0, `INSERT INTO t (id, ratio, amount) VALUES (5, ' 1e3 ', '.5')`),
			difftest.Q(0, `SELECT ratio = 1000, amount = 0.5 FROM t WHERE id = 5`),
			difftest.S(0, `INSERT INTO t (id, name) VALUES (6, 2)`),
			difftest.Q(0, `SELECT id FROM t WHERE name = '02'`),
			difftest.S(0, `UPDATE t SET amount = ' 7 ' WHERE id = 2`),
			difftest.Q(0, `SELECT id FROM t WHERE amount = 7 ORDER BY id`),
		},
	},
	{
		Name:   "numeric and float arithmetic",
		Schema: valueSchema, Seed: valueSeed, Conns: 1,
		Steps: []difftest.Step{
			difftest.Q(0, `SELECT id, amount / 2 = 0.75 FROM t WHERE id = 10`),
			difftest.Q(0, `SELECT (amount * 2) / 2 = 1.5 FROM t WHERE id = 10`),
			difftest.Q(0, `SELECT ratio / 4 = 0.5 FROM t WHERE id = 9`),
			difftest.Q(0, `SELECT sum(amount) > 208 FROM t`),
			difftest.Q(0, `SELECT floor(3) / 2 = 1.5, abs(-3) / 2`),
			difftest.Q(0, `SELECT (1.5 * 2) / 2 = 1.5, -(1.5 * 2) / 2 = -1.5`),
			difftest.Q(0, `SELECT id FROM t WHERE id * 1000000 = 9000000.0`),
			difftest.Q(0, `SELECT id FROM t ORDER BY CASE WHEN id = 2 THEN 'inf'::float8 - 'inf'::float8 ELSE ratio END DESC NULLS LAST, id LIMIT 2`),
			difftest.Q(0, `SELECT count(*) FROM (SELECT DISTINCT CASE WHEN id = 1 THEN 1000000 ELSE 1000000.0 END FROM t) s`),
			difftest.Q(0, `SELECT count(*) FROM (SELECT 1 FROM t GROUP BY CASE WHEN id = 1 THEN 1000000 ELSE 1000000.0 END) s`),
			difftest.Q(0, `SELECT count(*) FROM (SELECT 1000000 UNION SELECT 1000000.0) s`),
			difftest.Q(0, `SELECT count(DISTINCT CASE WHEN id = 1 THEN 1000000 ELSE 1000000.0 END) FROM t`),
			difftest.Q(0, `SELECT (CASE WHEN id > 0 THEN 1 ELSE 1.5 END) / 2 = 0.5 FROM t WHERE id = 1`),
			difftest.Q(0, `SELECT sum(CASE WHEN id > 0 THEN 1 ELSE 1.5 END) / 2 = 0.5 FROM t WHERE id = 1`),
			difftest.Q(0, `SELECT COALESCE(NULL, 1, 1.5) / 2 = 0.5, greatest(1, 0.5) / 2 = 0.5`),
			difftest.Q(0, `SELECT (CASE WHEN true THEN 1 ELSE -1.5 END) / 2 = 0.5, (CASE WHEN true THEN 1 ELSE 2 * 0.5 END) / 2 = 0.5`),
			difftest.Q(0, `SELECT (CASE WHEN true THEN 1 ELSE CASE WHEN false THEN 2.5 END END) / 2 = 0.5, COALESCE(1, round(2.5)) / 2 = 0.5`),
			difftest.Q(0, `SELECT NULLIF(1, 2.5) / 2 = 0.5`),
			difftest.Q(0, `SELECT count(*) FROM t HAVING NULLIF(count(*), 2.5) / 8 = 0.5`),
		},
	},
	{
		Name:   "casts to numbers",
		Schema: valueSchema, Seed: valueSeed, Conns: 1,
		Steps: []difftest.Step{
			difftest.Q(0, `SELECT '10'::int > '9'::int, ' 01 '::int = 1, '1.50'::numeric = 1.5`),
			difftest.Q(0, `SELECT 1.6::int, (-1.4)::smallint, true::int`),
			difftest.Q(0, `SELECT 'abc'::int`),
			difftest.Q(0, `SELECT 'not_a_number'::int`),
			difftest.Q(0, `SELECT '1_000_'::int`),
			difftest.Q(0, `SELECT '40000'::smallint`),
			difftest.Q(0, `SELECT 3000000000::int`),
			difftest.Q(0, `SELECT '9223372036854775808'::bigint`),
			difftest.Q(0, `SELECT '1e400'::float8`),
			difftest.Q(0, `SELECT '1e3'::numeric = 1000, 'inf'::float8 > 1e308`),
		},
	},
	{
		Name:   "untyped literal compared with a boolean",
		Schema: []string{`CREATE TABLE e (id int PRIMARY KEY, active bool)`},
		Seed:   []string{`INSERT INTO e VALUES (1, true), (2, false)`},
		Conns:  1,
		Steps: []difftest.Step{
			difftest.Q(0, `SELECT id FROM e WHERE active = 't' ORDER BY id`),
			difftest.Q(0, `SELECT id FROM e WHERE active = ' OFF ' ORDER BY id`),
			difftest.Q(0, `SELECT true = 'yes', true = ' TRUE ', true = 'on', true = '1', false = 'of', false = 'n'`),
			difftest.Q(0, `SELECT true = ANY (ARRAY['yes', false])`),
			difftest.Q(0, `SELECT true = 'o'`),
			difftest.Q(0, `SELECT true = 'maybe'`),
		},
	},
	{
		Name: "row comparison",
		Schema: []string{
			`CREATE TABLE p (a int, b int, name text, PRIMARY KEY (a, b))`,
		},
		Seed:  []string{`INSERT INTO p VALUES (9, 1, 'x'), (10, 1, 'y'), (2, 5, 'z'), (9, 3, NULL)`},
		Conns: 1,
		Steps: []difftest.Step{
			difftest.Q(0, `SELECT a, b FROM p WHERE (a, b) > (9, 1) ORDER BY a, b`),
			difftest.Q(0, `SELECT a, b FROM p WHERE (a, b) <= (9, 1) ORDER BY a, b`),
			difftest.Q(0, `SELECT a, b FROM p WHERE (a, b) = ('09', 1)`),
			difftest.Q(0, `SELECT a, b FROM p WHERE (a, b) <> (9, 1) ORDER BY a, b`),
			difftest.Q(0, `SELECT a, b FROM p WHERE (a, b) IN ((2, 5), ('10', 1)) ORDER BY a`),
			difftest.Q(0, `SELECT a, b FROM p WHERE (a, name) = (9, NULL)`),
			difftest.Q(0, `SELECT a, b FROM p WHERE NOT ((a, name) = (10, NULL)) ORDER BY a, b`),
			difftest.Q(0, `SELECT a, b FROM p WHERE (a * 1000000, b) > (9000000.0, 2) ORDER BY a, b`),
			difftest.Q(0, `SELECT count(*) FROM p WHERE (a, name) > (0, 'x')`),
			difftest.Q(0, `SELECT a, b FROM p WHERE (a, name) < (9, 'y') ORDER BY a, b`),
			difftest.Q(0, `SELECT a, b FROM p WHERE (a, b) = (SELECT a, b FROM p WHERE name = 'y')`),
			difftest.Q(0, `SELECT a, b FROM p WHERE (a, b) >= (SELECT 9, 2) ORDER BY a, b`),
			difftest.Q(0, `SELECT a, b FROM p WHERE (a, name) = (SELECT a, name FROM p WHERE b = 3)`),
			difftest.Q(0, `SELECT count(*) FROM p WHERE (a, b) <> (SELECT a, b FROM p WHERE a = 0)`),
			difftest.Q(0, `SELECT count(*) FROM p WHERE (a, b) = (SELECT a, b FROM p WHERE a = 9)`),
		},
	},
	{
		Name: "AND, OR and row comparisons over aggregates in HAVING",
		Schema: []string{
			`CREATE TABLE l (id int PRIMARY KEY, g int NOT NULL, k text, at int)`,
		},
		Seed: []string{
			`INSERT INTO l VALUES (1, 1, 'env', 5), (2, 1, 'team', 3), (3, 2, 'env', 3), (4, 3, 'env', 7), (5, 3, NULL, NULL), (6, 4, NULL, NULL)`,
		},
		Conns: 1,
		Steps: []difftest.Step{
			difftest.Q(0, `SELECT g FROM l GROUP BY g HAVING count(DISTINCT k) = 1 AND g < 3 ORDER BY g`),
			difftest.Q(0, `SELECT g FROM l GROUP BY g HAVING count(*) = 1 OR g = 1 ORDER BY g`),
			difftest.Q(0, `SELECT g FROM l GROUP BY g HAVING count(*) > 1 AND max(at) > 5 ORDER BY g`),
			difftest.Q(0, `SELECT g FROM l GROUP BY g HAVING max(at) > 4 OR min(k) = 'team' ORDER BY g`),
			difftest.Q(0, `SELECT g FROM l GROUP BY g HAVING (max(at) > 4 OR max(at) < 4) AND count(*) < 2 ORDER BY g`),
			difftest.Q(0, `SELECT g, min(at) FROM l GROUP BY g HAVING (min(at), g) >= (3, 2) ORDER BY min(at), g`),
			difftest.Q(0, `SELECT g FROM l GROUP BY g HAVING (min(at), g) < (5, 9) ORDER BY g`),
			difftest.Q(0, `SELECT g FROM l GROUP BY g HAVING (count(*), g) = (2, 3)`),
		},
	},
	{
		Name: "COLLATE and column collations on a C database",
		Schema: []string{
			`CREATE TABLE w (id int PRIMARY KEY, name text, code text COLLATE "C")`,
		},
		Seed:  []string{`INSERT INTO w VALUES (1, 'a', 'a'), (2, 'B', 'B'), (3, '_c', '_c'), (4, 'A-1', 'A-1'), (5, 'a1', 'a1'), (6, 'b', 'b')`},
		Conns: 1,
		Steps: []difftest.Step{
			difftest.Q(0, `SELECT id FROM w ORDER BY name`),
			difftest.Q(0, `SELECT id FROM w ORDER BY code DESC`),
			difftest.Q(0, `SELECT id FROM w ORDER BY name COLLATE "C"`),
			difftest.Q(0, `SELECT id FROM w ORDER BY name COLLATE "POSIX" DESC`),
			difftest.Q(0, `SELECT id FROM w ORDER BY name COLLATE pg_catalog."C"`),
			difftest.Q(0, `SELECT id FROM w ORDER BY name COLLATE "default"`),
			difftest.Q(0, `SELECT id FROM w WHERE name COLLATE "C" < 'a' ORDER BY id`),
			difftest.Q(0, `SELECT id FROM w WHERE code > name ORDER BY id`),
			difftest.Q(0, `SELECT min(code) = 'A-1', max(name COLLATE "C") = 'b' FROM w`),
			difftest.Q(0, `SELECT greatest(name, code) = name FROM w WHERE id = 3`),
		},
	},
	{
		Name: "IN and NOT IN over a subquery with NULLs",
		Schema: []string{
			`CREATE TABLE p (a int, b int, name text, PRIMARY KEY (a, b))`,
		},
		Seed:  []string{`INSERT INTO p VALUES (9, 1, 'x'), (10, 1, 'y'), (2, 5, 'z'), (9, 3, NULL)`},
		Conns: 1,
		Steps: []difftest.Step{
			difftest.Q(0, `SELECT count(*) FROM p WHERE (a, name) NOT IN (SELECT 9, NULL)`),
			difftest.Q(0, `SELECT count(*) FROM p WHERE a NOT IN (SELECT NULL::int)`),
			difftest.Q(0, `SELECT count(*) FROM p WHERE NULL::int NOT IN (SELECT a FROM p WHERE a < 0)`),
			difftest.Q(0, `SELECT count(*) FROM p WHERE a IN (SELECT a FROM p WHERE name IS NULL)`),
		},
	},
	{
		Name:   "bigint keys above 2^53",
		Schema: []string{`CREATE TABLE s (id int8 PRIMARY KEY)`},
		Seed:   []string{`INSERT INTO s VALUES (9007199254740992), (9007199254740993)`},
		Conns:  1,
		Steps: []difftest.Step{
			difftest.Q(0, `SELECT id FROM s WHERE id > 9007199254740992`),
			difftest.Q(0, `SELECT id FROM s ORDER BY id DESC LIMIT 1`),
			difftest.Q(0, `SELECT id FROM s WHERE id > 9007199254740992.0`),
			difftest.S(0, `INSERT INTO s VALUES ('9007199254740993')`),
		},
	},
	{
		Name:   "numeric keys written in different forms",
		Schema: []string{`CREATE TABLE u (n numeric PRIMARY KEY)`},
		Seed:   []string{`INSERT INTO u VALUES (1000000)`},
		Conns:  1,
		Steps: []difftest.Step{
			difftest.S(0, `INSERT INTO u VALUES ('1000000')`),
			difftest.S(0, `INSERT INTO u VALUES (1000000.0)`),
			difftest.S(0, `INSERT INTO u VALUES (1e6)`),
			difftest.S(0, `INSERT INTO u VALUES ('-0')`),
			difftest.S(0, `INSERT INTO u VALUES (0)`),
		},
	},
	{
		Name:   "integer arithmetic and rounding",
		Schema: valueSchema, Seed: valueSeed, Conns: 1,
		Steps: []difftest.Step{
			difftest.Q(0, `SELECT 7 / 2, -7 / 2, 7 % 2, -7 % 3, 7 % -3, 10 / 4, 10 / 4.0 = 2.5`),
			difftest.Q(0, `SELECT id FROM t WHERE id / 2 = 4`),
			difftest.Q(0, `SELECT id / 2 FROM t ORDER BY id`),
			difftest.Q(0, `SELECT avg(id) = 5.5, sum(id), power(2, 10) = 1024 FROM t`),
			difftest.Q(0, `SELECT id FROM t WHERE id % 2 = 1 ORDER BY id`),
			difftest.Q(0, `SELECT -id FROM t WHERE id = 2`),
			difftest.Q(0, `SELECT id FROM t WHERE amount + ratio = 102`),
			difftest.Q(0, `SELECT 1 / 0`),
			difftest.Q(0, `SELECT 1.0 / 0`),
			difftest.Q(0, `SELECT 1 % 0`),
			difftest.Q(0, `SELECT id FROM t WHERE 10 / (id - 1) > 0 AND id = 1`),
			difftest.Q(0, `SELECT round(2.5) = 3, round(-2.5) = -3, round(3.14159, 2) = 3.14, floor(-1.5) = -2, ceil(-1.5) = -1`),
			difftest.Q(0, `SELECT round(2.5::float8) = 2, round(0.5::float8) = 0, round(1.5::float8) = 2, round(-2.5::float8) = -2`),
			difftest.Q(0, `SELECT round(1.005, 2) = 1.01, round(1.25, 1) = 1.3, round(2.675, 2) = 2.68`),
			difftest.Q(0, `SELECT floor(ratio) = 1, ceil(ratio) = 2 FROM t WHERE id = 2`),
			difftest.Q(0, `SELECT 2.5::int, (-2.5)::int, 3.5::int, 2.5::float8::int, 1.4999::int`),
		},
	},
	{
		Name:   "casts to booleans and text",
		Schema: valueSchema, Seed: valueSeed, Conns: 1,
		Steps: []difftest.Step{
			difftest.Q(0, `SELECT 'yes'::bool, 'tr'::bool, ' true '::bool, 1::bool, 2::bool, 0::bool, 'f'::bool`),
			difftest.Q(0, `SELECT 'o'::bool`),
			difftest.Q(0, `SELECT '2'::bool`),
			difftest.Q(0, `SELECT true::text, true::int, false::int, true::text = 'true'`),
			difftest.Q(0, `SELECT 'true'::int`),
			difftest.Q(0, `SELECT 1::text = '1', 1::text, (-1)::text, 100::text`),
			difftest.Q(0, `SELECT id::text || 'x', id::text = name FROM t WHERE id = 2`),
			difftest.Q(0, `SELECT id::numeric = 1.0, id::float8 / 2 = 0.5, (id::text)::int = id FROM t WHERE id = 1`),
			difftest.Q(0, `SELECT id::varchar = '1', '1'::varchar = '1', name::text FROM t WHERE id = 1`),
			difftest.Q(0, `SELECT 'a' || 1, 'a' || NULL IS NULL, name || id FROM t WHERE id = 2`),
		},
	},
	{
		Name:   "number input forms",
		Schema: valueSchema, Seed: valueSeed, Conns: 1,
		Steps: []difftest.Step{
			difftest.Q(0, `SELECT ' +1 '::int, '1e2'::numeric = 100, ' 1.5 '::numeric = 1.5, '.5'::float8 = 0.5, '5.'::numeric = 5`),
			difftest.Q(0, `SELECT '1 2'::int`),
			difftest.Q(0, `SELECT ''::int`),
			difftest.Q(0, `SELECT '-'::int`),
			difftest.Q(0, `SELECT '1.0'::int`),
			difftest.Q(0, `SELECT '1e2'::int`),
			difftest.Q(0, `SELECT ''::numeric`),
			difftest.Q(0, `SELECT 'Infinity'::numeric > 1`),
			difftest.S(0, `INSERT INTO t (id) VALUES ('1e2')`),
			difftest.S(0, `INSERT INTO t (id) VALUES ('+3')`),
			difftest.S(0, `INSERT INTO t (id) VALUES ('')`),
			difftest.S(0, `INSERT INTO t (id, amount) VALUES (4, '')`),
			difftest.Q(0, `SELECT id FROM t WHERE id = ' 2 '`),
			difftest.Q(0, `SELECT id FROM t WHERE id = '+2'`),
		},
	},
	{
		Name:   "varchar and char lengths",
		Schema: []string{`CREATE TABLE m (id int PRIMARY KEY, v varchar(3), c char(3))`},
		Seed:   []string{`INSERT INTO m VALUES (1, 'ab', 'abc')`},
		Conns:  1,
		Steps: []difftest.Step{
			difftest.S(0, `INSERT INTO m (id, v) VALUES (2, 'abcd')`),
			difftest.S(0, `INSERT INTO m (id, v) VALUES (3, 'abc ')`),
			difftest.Q(0, `SELECT id FROM m WHERE v = 'abc'`),
			difftest.Q(0, `SELECT length(v), v FROM m WHERE id = 3`),
			difftest.S(0, `INSERT INTO m (id, c) VALUES (4, 'abcd')`),
			difftest.S(0, `INSERT INTO m (id, c) VALUES (7, 'abc  ')`),
			difftest.Q(0, `SELECT c, length(c) FROM m WHERE id = 7`),
			difftest.Q(0, `SELECT id FROM m WHERE c = 'abc' ORDER BY id`),
			difftest.S(0, `UPDATE m SET v = 'xyzw' WHERE id = 1`),
			difftest.S(0, `INSERT INTO m (id, v) VALUES (5, 12)`),
			difftest.S(0, `INSERT INTO m (id, v) VALUES (6, 1234)`),
			difftest.Q(0, `SELECT id FROM m WHERE v = '12'`),
		},
	},
	{
		Name:   "numeric precision and scale",
		Schema: []string{`CREATE TABLE m (id int PRIMARY KEY, price numeric(10,2), small numeric(4,1))`},
		Seed:   []string{`INSERT INTO m (id, price) VALUES (1, 1.00)`},
		Conns:  1,
		Steps: []difftest.Step{
			difftest.S(0, `INSERT INTO m (id, price) VALUES (5, 1.005)`),
			difftest.Q(0, `SELECT price = 1.01, price = 1.005 FROM m WHERE id = 5`),
			difftest.S(0, `INSERT INTO m (id, price) VALUES (6, '2.999')`),
			difftest.Q(0, `SELECT price = 3 FROM m WHERE id = 6`),
			difftest.S(0, `INSERT INTO m (id, price) VALUES (7, 1e3)`),
			difftest.S(0, `UPDATE m SET price = price * 1.1 WHERE id = 7`),
			difftest.Q(0, `SELECT price = 1100 FROM m WHERE id = 7`),
			difftest.S(0, `INSERT INTO m (id, price) VALUES (8, 100.5)`),
			difftest.S(0, `UPDATE m SET price = price * 1.1 WHERE id = 8`),
			difftest.Q(0, `SELECT price = 110.55 FROM m WHERE id = 8`),
			difftest.S(0, `INSERT INTO m (id, price) VALUES (13, 2.675)`),
			difftest.Q(0, `SELECT price = 2.68 FROM m WHERE id = 13`),
			difftest.S(0, `INSERT INTO m (id, small) VALUES (9, 999.95)`),
			difftest.S(0, `INSERT INTO m (id, small) VALUES (10, 999.94)`),
			difftest.Q(0, `SELECT small = 999.9 FROM m WHERE id = 10`),
			difftest.S(0, `INSERT INTO m (id, small) VALUES (11, -1000)`),
			difftest.S(0, `INSERT INTO m (id, small) VALUES (12, -0.05)`),
			difftest.Q(0, `SELECT small = -0.1 FROM m WHERE id = 12`),
			difftest.Q(0, `SELECT id FROM m WHERE price > 2 ORDER BY id`),
		},
	},
	{
		Name:   "numeric arithmetic",
		Schema: []string{`CREATE TABLE m (id int PRIMARY KEY, price numeric(10,2))`},
		Seed:   []string{`INSERT INTO m (id, price) VALUES (1, 0.10), (2, 0.20), (3, 10.00)`},
		Conns:  1,
		Steps: []difftest.Step{
			difftest.Q(0, `SELECT 0.1 + 0.2 = 0.3, 1.0 / 32 = 0.03125, 1.0 / 3 > 0.3333`),
			difftest.Q(0, `SELECT sum(price) > 0.29, sum(price) < 0.31, avg(price) < 0.16 FROM m WHERE id IN (1, 2)`),
			difftest.Q(0, `SELECT id FROM m WHERE price * 1.1 > 0.2 ORDER BY id`),
			difftest.S(0, `UPDATE m SET price = price / 3 WHERE id = 3`),
			difftest.Q(0, `SELECT price = 3.33 FROM m WHERE id = 3`),
		},
	},
	{
		Name: "limits set by ALTER COLUMN TYPE",
		// DDL runs once, before the rows, as a migration does; the rewrite
		// of rows an ALTER finds is covered by the unit tests.
		Schema: []string{
			`CREATE TABLE m (id int PRIMARY KEY, price numeric, v text, n int)`,
			`ALTER TABLE m ALTER COLUMN price TYPE numeric(4,1)`,
			`ALTER TABLE m ALTER COLUMN v TYPE varchar(3)`,
			`ALTER TABLE m ALTER COLUMN n TYPE numeric`,
		},
		Seed:  []string{`INSERT INTO m VALUES (1, 1.05, 'abc ', 1)`},
		Conns: 1,
		Steps: []difftest.Step{
			difftest.Q(0, `SELECT price = 1.1, v, length(v), n / 2 = 0.5 FROM m WHERE id = 1`),
			difftest.S(0, `INSERT INTO m (id, price, v) VALUES (2, 2.25, 'abcd')`),
			difftest.S(0, `INSERT INTO m (id, price, v) VALUES (3, 999.95, 'x')`),
			difftest.S(0, `INSERT INTO m (id, price, v) VALUES (4, 2.25, 'xy')`),
			difftest.S(0, `INSERT INTO m (id, price) VALUES (5, 'Infinity')`),
			difftest.S(0, `INSERT INTO m (id, n) VALUES (6, 'Infinity')`),
			difftest.Q(0, `SELECT price = 2.3 FROM m WHERE id = 4`),
			difftest.Q(0, `SELECT id FROM m ORDER BY id`),
		},
	},
	{
		Name: "other ALTER forms and column limits",
		Schema: []string{
			`CREATE TABLE m (id int PRIMARY KEY, price numeric, v text, n int)`,
			`ALTER TABLE m ADD COLUMN x numeric(4,1) DEFAULT 1.25`,
			`ALTER TABLE m ADD COLUMN w varchar(3) DEFAULT 'abc '`,
			`ALTER TABLE m ALTER COLUMN v TYPE varchar(4)`,
			`ALTER TABLE m ALTER COLUMN v TYPE text`,
			`ALTER TABLE m ALTER COLUMN n TYPE text`,
			`ALTER TABLE m ALTER COLUMN price SET DEFAULT 2.555`,
			`ALTER TABLE m ALTER COLUMN price TYPE numeric(4,1)`,
			`ALTER TABLE m RENAME COLUMN price TO cost`,
			`ALTER TABLE m ALTER COLUMN x TYPE numeric(5,2)`,
		},
		Seed:  []string{`INSERT INTO m (id, v, n) VALUES (1, 'abcde', 7)`},
		Conns: 1,
		Steps: []difftest.Step{
			difftest.Q(0, `SELECT x = 1.25, w, length(w), cost = 2.6 FROM m WHERE id = 1`),
			difftest.Q(0, `SELECT id FROM m WHERE n = '7'`),
			difftest.S(0, `INSERT INTO m (id, cost) VALUES (4, 1.005)`),
			difftest.Q(0, `SELECT cost = 1.0 FROM m WHERE id = 4`),
			difftest.S(0, `INSERT INTO m (id, x) VALUES (5, 1.005)`),
			difftest.Q(0, `SELECT x = 1.01 FROM m WHERE id = 5`),
			difftest.S(0, `INSERT INTO m (id, w) VALUES (6, 'abcd')`),
		},
	},
	{
		Name:   "column limits with constraints and defaults",
		Schema: []string{`CREATE TABLE m (id int PRIMARY KEY, price numeric(4,1) DEFAULT 1.25 CHECK (price > 0), v varchar(3) UNIQUE, c char(2) DEFAULT 'ab', u numeric(4,1) UNIQUE)`},
		Seed:   []string{`INSERT INTO m (id) VALUES (1)`},
		Conns:  1,
		Steps: []difftest.Step{
			difftest.Q(0, `SELECT price = 1.3, c FROM m WHERE id = 1`),
			difftest.S(0, `INSERT INTO m (id, price) VALUES (2, 0.04)`),
			difftest.S(0, `INSERT INTO m (id, price) VALUES (3, 0.05)`),
			difftest.Q(0, `SELECT price = 0.1 FROM m WHERE id = 3`),
			difftest.S(0, `INSERT INTO m (id, v) VALUES (4, 'abc')`),
			difftest.S(0, `INSERT INTO m (id, v) VALUES (5, 'abc ')`),
			difftest.S(0, `INSERT INTO m (id, u) VALUES (6, 1.04)`),
			difftest.S(0, `INSERT INTO m (id, u) VALUES (7, 1.03)`),
			difftest.S(0, `INSERT INTO m (id, u) VALUES (8, -1.05)`),
			difftest.Q(0, `SELECT u = -1.1 FROM m WHERE id = 8`),
			difftest.S(0, `INSERT INTO m (id, u) VALUES (9, -0.04)`),
			difftest.Q(0, `SELECT u = 0, u = -0.0 FROM m WHERE id = 9`),
			difftest.S(0, `UPDATE m SET price = price + 0.05 WHERE id = 1`),
			difftest.Q(0, `SELECT price = 1.4 FROM m WHERE id = 1`),
			difftest.S(0, `UPDATE m SET price = price / 3 WHERE id = 1`),
			difftest.Q(0, `SELECT price = 0.5 FROM m WHERE id = 1`),
			difftest.S(0, `INSERT INTO m (id, price) VALUES (10, '1.05'::numeric)`),
			difftest.Q(0, `SELECT price = 1.1 FROM m WHERE id = 10`),
			difftest.Q(0, `SELECT sum(price) = 3.0 FROM m WHERE id IN (1, 3, 10)`),
			difftest.S(0, `UPDATE m SET u = 1.04 WHERE id = 7`),
			difftest.S(0, `INSERT INTO m (id, price) VALUES (11, DEFAULT)`),
			difftest.Q(0, `SELECT price = 1.3 FROM m WHERE id = 11`),
			difftest.Q(0, `SELECT id FROM m WHERE v = 'abc'`),
			difftest.Q(0, `SELECT id FROM m WHERE u = 1.0 ORDER BY id`),
			difftest.S(0, `INSERT INTO m (id, c) VALUES (12, 'abc')`),
			difftest.S(0, `INSERT INTO m (id, c) VALUES (13, 'ab ')`),
			difftest.Q(0, `SELECT id FROM m WHERE c = 'ab' ORDER BY id`),
		},
	},
	{
		Name:   "set operations",
		Schema: valueSchema, Seed: valueSeed, Conns: 1,
		Steps: []difftest.Step{
			difftest.Q(0, `SELECT x FROM (SELECT NULL AS x UNION SELECT 1) s ORDER BY x`),
			difftest.Q(0, `SELECT x / 2 = 0.5 FROM (SELECT 1 AS x UNION SELECT NULL UNION SELECT 2.5) s WHERE x = 1`),
			difftest.Q(0, `SELECT count(*) FROM (SELECT id FROM t UNION ALL SELECT id FROM t) s`),
			difftest.Q(0, `SELECT id FROM t EXCEPT ALL SELECT 1 ORDER BY id`),
			difftest.Q(0, `SELECT count(*) FROM (SELECT name FROM t UNION ALL SELECT name FROM t INTERSECT ALL SELECT name FROM t) s`),
			difftest.Q(0, `SELECT id FROM t UNION SELECT 100 ORDER BY id DESC LIMIT 2`),
			difftest.Q(0, `SELECT count(*) FROM (SELECT ratio FROM t UNION SELECT 1.5 UNION SELECT 2) s`),
			difftest.Q(0, `SELECT count(*) FROM (SELECT NULL::int UNION SELECT NULL) s`),
			difftest.Q(0, `SELECT count(*) FROM (SELECT name FROM t EXCEPT SELECT NULL) s`),
			difftest.Q(0, `SELECT count(*) FROM (SELECT name FROM t INTERSECT SELECT NULL) s`),
			difftest.Q(0, `SELECT id FROM t WHERE id IN (SELECT id FROM t WHERE id < 5 UNION SELECT 10) ORDER BY id`),
			difftest.Q(0, `SELECT x, count(*) FROM (SELECT id % 2 AS x FROM t UNION ALL SELECT 1) s GROUP BY x ORDER BY x`),
			difftest.Q(0, `SELECT count(*) FROM (SELECT true UNION SELECT false UNION SELECT true) s`),
			difftest.Q(0, `SELECT count(*) FROM (SELECT 1.0 UNION SELECT 1.00 UNION SELECT 1e0) s`),
			difftest.Q(0, `SELECT x FROM (SELECT 'b' AS x UNION SELECT 'a' UNION SELECT 'a ') s ORDER BY x`),
			difftest.Q(0, `SELECT count(*) FROM (SELECT id FROM t UNION SELECT id::bigint FROM t) s`),
			difftest.Q(0, `SELECT sum(x) = 10.5 FROM (SELECT 1 AS x UNION ALL SELECT 9.5) s`),
			difftest.Q(0, `SELECT x = 1.5 FROM (SELECT amount AS x FROM t UNION SELECT 7) s ORDER BY x LIMIT 1`),
		},
	},
	{
		Name:   "branches of CASE, COALESCE, NULLIF, GREATEST and LEAST",
		Schema: valueSchema, Seed: valueSeed, Conns: 1,
		Steps: []difftest.Step{
			difftest.Q(0, `SELECT COALESCE(NULL::numeric, 1) / 2 = 0.5, COALESCE(amount, 0) / 2 = 0.75 FROM t WHERE id = 10`),
			difftest.Q(0, `SELECT COALESCE(ratio, 0) / 4 = 0.5 FROM t WHERE id = 9`),
			difftest.Q(0, `SELECT CASE id WHEN 1 THEN 'one' WHEN 2 THEN 'two' ELSE 'many' END FROM t ORDER BY id`),
			difftest.Q(0, `SELECT CASE WHEN id = 1 THEN NULL ELSE 1 END FROM t ORDER BY id`),
			difftest.Q(0, `SELECT NULLIF(amount, 7) IS NULL, NULLIF(id, '1') IS NULL FROM t ORDER BY id`),
			difftest.Q(0, `SELECT GREATEST(amount, ratio) > 2, LEAST(name, 'b') FROM t WHERE id = 2`),
			difftest.Q(0, `SELECT sum(CASE WHEN id > 2 THEN 1 END), sum(CASE WHEN id > 100 THEN 1 END) FROM t`),
			difftest.Q(0, `SELECT CASE WHEN id > 5 THEN 'big' END IS NULL, CASE WHEN id > 5 THEN id END FROM t ORDER BY id`),
			difftest.Q(0, `SELECT COALESCE(name, id::text) FROM t ORDER BY id`),
			difftest.Q(0, `SELECT COALESCE(NULL, NULL, 3), COALESCE(NULL::text, 'x'), GREATEST(1, 2.5) = 2.5, LEAST(1, '0') = 0`),
			difftest.Q(0, `SELECT id FROM t WHERE CASE WHEN ratio IS NULL THEN amount ELSE ratio END > 1 ORDER BY id`),
			difftest.Q(0, `SELECT id FROM t WHERE COALESCE(ratio, amount) < 2 ORDER BY id`),
			difftest.Q(0, `SELECT CASE WHEN id = 1 THEN 1 WHEN id = 2 THEN 2.5 ELSE 3 END * 2 = 2 FROM t WHERE id = 1`),
			difftest.Q(0, `SELECT (CASE WHEN id = 1 THEN 1 ELSE '2' END) / 2 FROM t ORDER BY id`),
			difftest.Q(0, `SELECT COALESCE('5', 1) / 2`),
			difftest.Q(0, `SELECT COALESCE(NULL, '5', 1) / 2`),
			difftest.Q(0, `SELECT CASE WHEN true THEN '5' ELSE 1.0 END / 2 = 2.5`),
			difftest.Q(0, `SELECT (CASE WHEN id = 1 THEN 1 ELSE ratio END) / 2 = 0.5, COALESCE(1, amount) / 2 = 0.5, (CASE WHEN id = 1 THEN 1 ELSE id END) / 2 FROM t WHERE id = 1`),
			difftest.Q(0, `SELECT (CASE WHEN id = 1 THEN 1 ELSE '3' END) / 2, (CASE WHEN id = 1 THEN 1 ELSE amount END) / 2 = 0.5 FROM t WHERE id = 1`),
		},
	},
	{
		Name:   "text operations",
		Schema: valueSchema, Seed: valueSeed, Conns: 1,
		Steps: []difftest.Step{
			difftest.Q(0, `SELECT id::text || name, 'x' || id || 'y', length(id::text), (id + 1)::text FROM t WHERE id = 2`),
			difftest.Q(0, `SELECT upper(name) || lower('B'), name || '' = name, NULL || 'a' IS NULL FROM t WHERE id = 1`),
			difftest.Q(0, `SELECT id FROM t WHERE id::text = '1' OR id::text = name ORDER BY id`),
			difftest.Q(0, `SELECT id FROM t WHERE name = 'a' || '' ORDER BY id`),
			difftest.Q(0, `SELECT id FROM t WHERE id::text LIKE '1%' ORDER BY id`),
			difftest.Q(0, `SELECT id FROM t WHERE length(name) = 1 ORDER BY id`),
			difftest.Q(0, `SELECT id::text::int, ('0' || id)::int FROM t WHERE id = 9`),
			difftest.Q(0, `SELECT 'a' || true, 'a' || id::bigint, 1::text || 2::text FROM t WHERE id = 1`),
			difftest.Q(0, `SELECT concat(name, id) FROM t WHERE id = 2`),
			difftest.Q(0, `SELECT name FROM t WHERE name > 'a' AND name < 'z' ORDER BY name`),
			difftest.Q(0, `SELECT lower('ABC') = 'abc', upper(NULL) IS NULL, length(''), 'abc' < 'abd'`),
		},
	},
	{
		Name:   "NULL semantics",
		Schema: valueSchema, Seed: valueSeed, Conns: 1,
		Steps: []difftest.Step{
			difftest.Q(0, `SELECT NULL = NULL, NULL <> NULL, NULL IS NULL, NOT NULL::bool`),
			difftest.Q(0, `SELECT count(*) FROM t WHERE id = NULL`),
			difftest.Q(0, `SELECT count(*) FROM t WHERE NOT (id = NULL)`),
			difftest.Q(0, `SELECT count(*) FROM t WHERE id <> NULL`),
			difftest.Q(0, `SELECT coalesce(name, 'none') FROM t ORDER BY id`),
			difftest.Q(0, `SELECT greatest(1, NULL, 3), least(NULL, NULL) IS NULL, least(2, NULL, 1)`),
			difftest.Q(0, `SELECT id FROM t WHERE NOT (name = 'a') ORDER BY id`),
			difftest.Q(0, `SELECT id FROM t WHERE name <> 'a' OR name IS NULL ORDER BY id`),
			difftest.Q(0, `SELECT NULL AND false, NULL OR true, NULL AND true, NULL OR false`),
			difftest.Q(0, `SELECT CASE WHEN NULL THEN 1 ELSE 2 END, CASE name WHEN NULL THEN 1 ELSE 2 END FROM t WHERE id = 9`),
			difftest.Q(0, `SELECT CASE WHEN id = 1 THEN 'one' END IS NULL FROM t ORDER BY id`),
			difftest.Q(0, `SELECT NULL BETWEEN 1 AND 2, 5 BETWEEN 9 AND 2`),
			difftest.Q(0, `SELECT count(DISTINCT name), count(name), count(*), count(ratio) FROM t`),
			difftest.Q(0, `SELECT count(*) FROM (SELECT DISTINCT name FROM t) s`),
			difftest.Q(0, `SELECT count(*) FROM (SELECT ratio FROM t UNION SELECT NULL) s`),
			difftest.Q(0, `SELECT count(*) FROM (SELECT ratio FROM t UNION SELECT 2.0) s`),
			difftest.Q(0, `SELECT count(*) FROM (SELECT name FROM t UNION SELECT NULL) s`),
			difftest.Q(0, `SELECT name, count(*) FROM t GROUP BY name ORDER BY name NULLS FIRST`),
			difftest.Q(0, `SELECT sum(ratio) = 4, avg(ratio) > 1.3, max(ratio) = 2, min(amount) = 1.5, sum(amount) = 208 FROM t`),
			difftest.Q(0, `SELECT min(name), max(name) FROM t`),
			difftest.Q(0, `SELECT sum(id) FROM t WHERE false`),
			difftest.Q(0, `SELECT count(*), max(id) FROM t WHERE false`),
			difftest.Q(0, `SELECT 1 FROM t WHERE false GROUP BY id`),
			difftest.Q(0, `SELECT id FROM t EXCEPT SELECT 1 ORDER BY id`),
			difftest.Q(0, `SELECT count(*) FROM (SELECT name FROM t UNION ALL SELECT name FROM t) s`),
			difftest.Q(0, `SELECT DISTINCT ON (name) id FROM t ORDER BY name, id`),
		},
	},
	{
		Name:   "ordering",
		Schema: valueSchema, Seed: valueSeed, Conns: 1,
		Steps: []difftest.Step{
			difftest.Q(0, `SELECT id FROM t ORDER BY ratio`),
			difftest.Q(0, `SELECT id FROM t ORDER BY ratio DESC`),
			difftest.Q(0, `SELECT id FROM t ORDER BY name NULLS FIRST, id`),
			difftest.Q(0, `SELECT id FROM t ORDER BY ratio DESC NULLS LAST`),
			difftest.Q(0, `SELECT id FROM t ORDER BY name`),
			difftest.Q(0, `SELECT 'a' < 'B', 'a' < 'b', 'B' < 'a', '2' < 'a', 'Z' < 'a'`),
			difftest.Q(0, `SELECT id FROM t WHERE name > '1' ORDER BY id`),
			difftest.Q(0, `SELECT id FROM t WHERE name < 'b' ORDER BY id`),
			difftest.Q(0, `SELECT id FROM t ORDER BY amount DESC LIMIT 2 OFFSET 1`),
			difftest.Q(0, `SELECT id FROM t ORDER BY id LIMIT NULL`),
			difftest.Q(0, `SELECT id FROM t ORDER BY id OFFSET 10`),
			difftest.Q(0, `SELECT row_number() OVER (ORDER BY amount), id FROM t ORDER BY id`),
			difftest.Q(0, `SELECT rank() OVER (ORDER BY ratio DESC), id FROM t ORDER BY id`),
			difftest.Q(0, `SELECT count(*) OVER (), lag(id) OVER (ORDER BY id) FROM t ORDER BY id`),
		},
	},
	{
		Name:   "comparisons of numbers, text and rows",
		Schema: valueSchema, Seed: valueSeed, Conns: 1,
		Steps: []difftest.Step{
			difftest.Q(0, `SELECT 1 = 1.0, 1 < 1.5, 2 > 1.5, '1' = 1, '1' = '1.0', 1.0 = 1.00, 100 = 1e2`),
			difftest.Q(0, `SELECT id FROM t WHERE id = 1.0`),
			difftest.Q(0, `SELECT id FROM t WHERE id > 0.5 AND id < 1e1 ORDER BY id`),
			difftest.Q(0, `SELECT id FROM t WHERE id = 10.0000001`),
			difftest.Q(0, `SELECT id FROM t WHERE amount = 100.5`),
			difftest.Q(0, `SELECT id FROM t WHERE amount = 100.50`),
			difftest.Q(0, `SELECT id FROM t WHERE id BETWEEN '2' AND '9' ORDER BY id`),
			difftest.Q(0, `SELECT id FROM t WHERE amount BETWEEN 1 AND '100' ORDER BY id`),
			difftest.Q(0, `SELECT id FROM t WHERE id NOT BETWEEN 2 AND 9 ORDER BY id`),
			difftest.Q(0, `SELECT id FROM t WHERE id IN (1, 2.5)`),
			difftest.Q(0, `SELECT id FROM t WHERE id IN ('1', 2.5)`),
			difftest.Q(0, `SELECT count(*) FROM t WHERE id IN (NULL)`),
			difftest.Q(0, `SELECT count(*) FROM t WHERE id NOT IN (NULL, 1)`),
			difftest.Q(0, `SELECT id FROM t WHERE id NOT IN (2) ORDER BY id`),
			difftest.Q(0, `SELECT id FROM t WHERE id = ANY (ARRAY[1, 2]) ORDER BY id`),
			difftest.Q(0, `SELECT id FROM t WHERE id <> ALL (ARRAY[1, 2]) ORDER BY id`),
			difftest.Q(0, `SELECT id FROM t WHERE name <> ALL (ARRAY['a']) ORDER BY id`),
			difftest.Q(0, `SELECT count(*) FROM t WHERE (id, name) = (2, '2')`),
			difftest.Q(0, `SELECT id FROM t WHERE (id, name) IN ((1, 'a'), (10, 'x')) ORDER BY id`),
			difftest.Q(0, `SELECT id FROM t WHERE id = '1' OR name = 'x' ORDER BY id`),
			difftest.Q(0, `SELECT id FROM t WHERE coalesce(ratio, 0) < 1 ORDER BY id`),
			difftest.Q(0, `SELECT id FROM t WHERE amount > (SELECT avg(amount) FROM t) ORDER BY id`),
			difftest.Q(0, `SELECT id FROM t WHERE id = (SELECT min(id) FROM t)`),
			difftest.Q(0, `SELECT (SELECT count(*) FROM t) = 4, (SELECT name FROM t WHERE id = 9) IS NULL`),
			difftest.Q(0, `SELECT count(*) FROM t WHERE id = (SELECT id FROM t WHERE false)`),
			difftest.Q(0, `SELECT id FROM t WHERE id = (SELECT id FROM t)`),
			difftest.Q(0, `SELECT CASE WHEN id = 1 THEN 1 ELSE '2' END = 2 FROM t ORDER BY id`),
			difftest.Q(0, `SELECT (CASE WHEN false THEN 1 ELSE '3' END) / 2, (CASE WHEN false THEN 1.0 ELSE '3' END) / 2 = 1.5`),
			difftest.Q(0, `SELECT x / 2 = 0.5 FROM (SELECT 1 AS x UNION ALL SELECT 3.0) s ORDER BY x`),
			difftest.Q(0, `SELECT x / 2 = 0.5 FROM (SELECT 1 AS x UNION ALL SELECT 3.0 WHERE false) s`),
			difftest.Q(0, `SELECT (CASE WHEN true THEN 1 ELSE power(2, 2) END) / 2 = 0.5, (CASE WHEN true THEN 1 ELSE random() END) / 2 = 0.5`),
			difftest.Q(0, `SELECT count(*) FROM (SELECT 1 UNION SELECT 1.0) s`),
			difftest.Q(0, `SELECT 'a' || true, 'a' || 1, 'a' || id FROM t WHERE id = 1`),
			difftest.Q(0, `SELECT CASE WHEN id = 1 THEN name ELSE '2' END FROM t ORDER BY id`),
			difftest.Q(0, `SELECT greatest(name, 'b'), greatest(id, 1.5) = 1.5, least(id, '5') FROM t WHERE id = 1`),
			difftest.Q(0, `SELECT name LIKE 'a%', name LIKE '_', name ILIKE 'X', id::text LIKE '1%' FROM t ORDER BY id`),
		},
	},
	{
		Name:   "boolean column",
		Schema: []string{`CREATE TABLE e (id int PRIMARY KEY, active bool)`},
		Seed:   []string{`INSERT INTO e VALUES (1, true), (2, false), (3, NULL)`},
		Conns:  1,
		Steps: []difftest.Step{
			difftest.Q(0, `SELECT id FROM e WHERE active = 'yes'`),
			difftest.Q(0, `SELECT id FROM e WHERE active IN ('t', 'f') ORDER BY id`),
			difftest.Q(0, `SELECT id FROM e WHERE NOT active`),
			difftest.Q(0, `SELECT count(*) FROM e WHERE active`),
			difftest.Q(0, `SELECT id FROM e WHERE active AND id > 0`),
			difftest.Q(0, `SELECT id FROM e WHERE active OR id = 3`),
			difftest.Q(0, `SELECT id FROM e ORDER BY active, id`),
			difftest.Q(0, `SELECT id FROM e ORDER BY active DESC, id`),
			difftest.Q(0, `SELECT id FROM e WHERE active = (id = 1) ORDER BY id`),
			difftest.Q(0, `SELECT sum(CASE WHEN active THEN 1 ELSE 0 END), count(active), count(DISTINCT active) FROM e`),
			difftest.Q(0, `SELECT active::int, active::text FROM e ORDER BY id`),
			difftest.S(0, `UPDATE e SET active = NOT active WHERE id = 2`),
			difftest.Q(0, `SELECT id, active FROM e ORDER BY id`),
			difftest.Q(0, `SELECT id FROM e WHERE active = 'true'::bool ORDER BY id`),
		},
	},
	{
		Name:   "boolean column expressions and defaults",
		Schema: []string{`CREATE TABLE e (id int PRIMARY KEY, active bool DEFAULT false, n int)`},
		Seed:   []string{`INSERT INTO e VALUES (1, true, 1), (2, false, 2), (3, NULL, NULL)`},
		Conns:  1,
		Steps: []difftest.Step{
			difftest.Q(0, `SELECT id FROM e WHERE active = true`),
			difftest.Q(0, `SELECT id FROM e WHERE active IS NULL`),
			difftest.Q(0, `SELECT id FROM e ORDER BY active NULLS FIRST, id`),
			difftest.Q(0, `SELECT CASE WHEN active THEN 'y' ELSE 'n' END FROM e ORDER BY id`),
			difftest.Q(0, `SELECT coalesce(active, false), active AND NULL, active OR NULL FROM e ORDER BY id`),
			difftest.Q(0, `SELECT count(*) FROM e WHERE active = NULL`),
			difftest.Q(0, `SELECT id FROM e WHERE active <> false`),
			difftest.Q(0, `SELECT active::int + 1, sum(active::int) OVER () FROM e ORDER BY id`),
			difftest.Q(0, `SELECT id FROM e WHERE active IN (true) ORDER BY id`),
			difftest.Q(0, `SELECT id FROM e WHERE active = ANY (ARRAY[true]) ORDER BY id`),
			difftest.Q(0, `SELECT id FROM e WHERE NOT (active = false) ORDER BY id`),
			difftest.Q(0, `SELECT id FROM e WHERE (n > 1) = active ORDER BY id`),
			difftest.Q(0, `SELECT id FROM e WHERE active = (n = 1) ORDER BY id`),
			difftest.S(0, `INSERT INTO e (id) VALUES (4)`),
			difftest.Q(0, `SELECT active FROM e WHERE id = 4`),
			difftest.S(0, `UPDATE e SET active = n > 1 WHERE id IN (1, 2)`),
			difftest.Q(0, `SELECT id, active FROM e ORDER BY id`),
			difftest.S(0, `UPDATE e SET active = DEFAULT`),
			difftest.Q(0, `SELECT count(*) FROM e WHERE active`),
			difftest.Q(0, `SELECT max(active::int), min(active::int), count(DISTINCT active) FROM e`),
			difftest.Q(0, `SELECT id FROM e WHERE active = 'f' AND n IS NULL`),
			difftest.Q(0, `SELECT (active = true) IS NULL FROM e ORDER BY id`),
			difftest.Q(0, `SELECT true AND false, true OR false, NOT true, true = false, true < false, true > false`),
			difftest.Q(0, `SELECT id FROM e ORDER BY active DESC NULLS LAST, id`),
		},
	},
	{
		Name:   "text written to boolean and timestamp columns",
		Schema: []string{`CREATE TABLE e (id int PRIMARY KEY, at timestamptz, ts timestamp, active bool)`},
		Seed: []string{
			`INSERT INTO e VALUES (1, '2024-06-01 00:00:00+00', '2024-06-01 09:00:00', 'true')`,
			`INSERT INTO e VALUES (2, '2024-01-01T00:00:00Z', '2024-01-01', 'f')`,
			`INSERT INTO e VALUES (3, '2024-03-01 00:00:00+09', '2024-03-01 00:00:00+09', 'yes')`,
		},
		Conns: 1,
		Steps: []difftest.Step{
			difftest.Q(0, `SELECT id FROM e WHERE active ORDER BY id`),
			difftest.Q(0, `SELECT id FROM e WHERE NOT active ORDER BY id`),
			difftest.Q(0, `SELECT id FROM e ORDER BY at, id`),
			difftest.Q(0, `SELECT id FROM e ORDER BY ts, id`),
			difftest.Q(0, `SELECT id FROM e WHERE at > (SELECT at FROM e WHERE id = 3) ORDER BY id`),
			difftest.Q(0, `SELECT id FROM e WHERE ts < (SELECT ts FROM e WHERE id = 3) ORDER BY id`),
			difftest.Q(0, `SELECT count(DISTINCT active) FROM e`),
			difftest.S(0, `UPDATE e SET active = 'off', at = '2023-12-31 23:00:00-01:00' WHERE id = 1`),
			difftest.Q(0, `SELECT id FROM e WHERE active ORDER BY id`),
			difftest.Q(0, `SELECT id FROM e WHERE at = (SELECT at FROM e WHERE id = 2) ORDER BY id`),
			difftest.S(0, `INSERT INTO e (id, active) VALUES (5, 'maybe')`),
		},
	},
	{
		Name:   "timestamps rounded to their precision",
		Schema: []string{`CREATE TABLE p (id int PRIMARY KEY, at timestamptz(0) UNIQUE, ts timestamp(3), us timestamp)`},
		Seed: []string{
			`INSERT INTO p VALUES (1, '2024-01-01 00:00:00.4+00', '2024-01-01 00:00:00.1234', '2024-01-01 00:00:00.1234567')`,
			`INSERT INTO p VALUES (2, '2024-01-01 00:00:01.6+00', '2024-01-01 00:00:00.1231', '2024-01-01 00:00:00.123456')`,
		},
		Conns: 1,
		Steps: []difftest.Step{
			difftest.Q(0, `SELECT count(DISTINCT ts), count(DISTINCT us) FROM p`),
			difftest.Q(0, `SELECT id FROM p WHERE at > (SELECT at FROM p WHERE id = 1) + interval '1 second' ORDER BY id`),
			difftest.S(0, `INSERT INTO p (id, at) VALUES (3, '2024-01-01 00:00:00.2+00')`),
			difftest.S(0, `UPDATE p SET ts = '2024-01-01 00:00:00.9999' WHERE id = 1`),
			difftest.Q(0, `SELECT id FROM p WHERE ts > (SELECT us FROM p WHERE id = 1) ORDER BY id`),
		},
	},
	{
		Name:   "updates with old values and defaults",
		Schema: []string{`CREATE TABLE d (id int PRIMARY KEY, qty int DEFAULT 0 NOT NULL CHECK (qty >= 0), price numeric DEFAULT 1.50, note text DEFAULT 'x', a int, b int)`},
		Seed:   []string{`INSERT INTO d (id, a, b) VALUES (1, 1, 2)`},
		Conns:  1,
		Steps: []difftest.Step{
			difftest.Q(0, `SELECT qty, price = 1.5, note FROM d WHERE id = 1`),
			difftest.S(0, `UPDATE d SET a = b, b = a WHERE id = 1`),
			difftest.Q(0, `SELECT a, b FROM d WHERE id = 1`),
			difftest.S(0, `INSERT INTO d (id, qty) VALUES (2, DEFAULT)`),
			difftest.S(0, `UPDATE d SET qty = 5 WHERE id = 2`),
			difftest.S(0, `UPDATE d SET qty = DEFAULT WHERE id = 2`),
			difftest.Q(0, `SELECT qty FROM d WHERE id = 2`),
			difftest.S(0, `UPDATE d SET qty = -1 WHERE id = 2`),
			difftest.S(0, `UPDATE d SET qty = NULL WHERE id = 2`),
			difftest.S(0, `UPDATE d SET price = NULL WHERE id = 2`),
			difftest.Q(0, `SELECT count(*) FROM d WHERE price IS NULL`),
			difftest.S(0, `UPDATE d SET a = a + 1, b = a + 1 WHERE id = 1`),
			difftest.Q(0, `SELECT a, b FROM d WHERE id = 1`),
			difftest.S(0, `UPDATE d SET price = price + 1 WHERE id = 1`),
			difftest.Q(0, `SELECT price = 2.5 FROM d WHERE id = 1`),
			difftest.S(0, `UPDATE d SET price = '1e2', note = 7 WHERE id = 1`),
			difftest.Q(0, `SELECT price = 100, note FROM d WHERE id = 1`),
			difftest.Q(0, `UPDATE d SET qty = qty + 1 WHERE id = 1 RETURNING id, qty > 0`),
			difftest.S(0, `INSERT INTO d (id) VALUES (1) ON CONFLICT (id) DO NOTHING`),
			difftest.S(0, `INSERT INTO d (id, a) VALUES (1, 10) ON CONFLICT (id) DO UPDATE SET a = EXCLUDED.a + d.a`),
			difftest.Q(0, `SELECT a FROM d WHERE id = 1`),
			difftest.S(0, `INSERT INTO d (id, qty) VALUES (3, '2.0')`),
			difftest.S(0, `INSERT INTO d (id, qty) VALUES (3, 2.0)`),
			difftest.Q(0, `SELECT qty FROM d WHERE id = 3`),
		},
	},
	{
		// A string literal compared with a uuid is read by uuid input, so
		// it matches the row in another case, in braces or without hyphens,
		// and text that is no uuid fails the statement.
		Name: "string literals compared with a uuid column",
		Schema: []string{
			`CREATE TABLE u (id int PRIMARY KEY, u uuid UNIQUE, name text)`,
		},
		Seed: []string{
			`INSERT INTO u VALUES (1, '00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-000000000001')`,
			`INSERT INTO u VALUES (2, '00000000-0000-0000-0000-00000000000a', '00000000-0000-0000-0000-00000000000A')`,
			`INSERT INTO u VALUES (3, NULL, 'x')`,
		},
		Conns: 1,
		Steps: []difftest.Step{
			difftest.Q(0, `SELECT id FROM u WHERE u = '00000000-0000-0000-0000-00000000000A'`),
			difftest.Q(0, `SELECT id FROM u WHERE '{00000000-0000-0000-0000-00000000000a}' = u`),
			difftest.Q(0, `SELECT id FROM u WHERE u <> '0000000000000000000000000000000A' ORDER BY id`),
			difftest.Q(0, `SELECT id FROM u WHERE u IN ('00000000-0000-0000-0000-00000000000A', '00000000000000000000000000000001') ORDER BY id`),
			difftest.Q(0, `SELECT id FROM u WHERE u = ANY('{00000000-0000-0000-0000-00000000000A}') ORDER BY id`),
			difftest.Q(0, `SELECT id FROM u WHERE u::text = '00000000-0000-0000-0000-00000000000A'`),
			difftest.Q(0, `SELECT id FROM u ORDER BY u, id`),
			difftest.Q(0, `UPDATE u SET name = 'y' WHERE u = '00000000-0000-0000-0000-00000000000A' RETURNING id`),
			difftest.S(0, `INSERT INTO u (id, u) VALUES (4, '00000000-0000-0000-0000-00000000000A')`),
			difftest.Q(0, `SELECT id FROM u WHERE u = 'nope'`),
			difftest.Q(0, `SELECT id FROM u WHERE u IN ('00000000-0000-0000-0000-000000000001', 'nope')`),
			difftest.S(0, `DELETE FROM u WHERE u = 'nope'`),
		},
	},
	{
		// Postgres reads a string literal by its operand's type when it
		// plans the statement, so invalid input fails one that reaches no
		// row too.
		Name:   "invalid untyped input over no rows",
		Schema: []string{`CREATE TABLE z (id int PRIMARY KEY, u uuid, b bool, f float8)`},
		Conns:  1,
		Steps: []difftest.Step{
			difftest.Q(0, `SELECT id FROM z WHERE u = 'nope'`),
			difftest.Q(0, `SELECT id FROM z WHERE id = 'abc'`),
			difftest.Q(0, `SELECT id FROM z WHERE 'maybe' = b`),
			difftest.Q(0, `SELECT id FROM z WHERE f < 'x'`),
			difftest.Q(0, `SELECT id FROM z WHERE id IN (1, 'abc')`),
			difftest.Q(0, `SELECT 1 WHERE true OR 1 = 'abc'`),
			difftest.Q(0, `SELECT CASE 1 WHEN 'abc' THEN 1 END`),
			difftest.Q(0, `SELECT nullif(1, 'abc')`),
			difftest.Q(0, `SELECT id FROM z WHERE u = ANY('{nope}')`),
			difftest.Q(0, `SELECT id FROM z WHERE id = ANY('{1,abc}')`),
			difftest.Q(0, `SELECT id FROM z WHERE u = ANY('{00000000-0000-0000-0000-00000000000A}')`),
			difftest.S(0, `UPDATE z SET b = true WHERE u = 'nope'`),
			difftest.Q(0, `SELECT id FROM z WHERE id = '1' AND u = '00000000-0000-0000-0000-00000000000A'`),
		},
	},
}

func TestDiffValues(t *testing.T) {
	for _, c := range valueCases {
		t.Run(c.Name, func(t *testing.T) {
			t.Parallel()
			difftest.Run(t, backend{}, c)
		})
	}
}
