package postgres_test

import (
	"testing"

	"github.com/k1LoW/detest/internal/difftest"
)

// The write cases compare the outcomes of writes with Postgres: unique
// indexes and the waits of concurrent inserts, ON CONFLICT and its arbiters,
// foreign keys and when they are checked, sequences, and the snapshot the
// queries of a write read.
var writeCases = []difftest.Case{
	{
		Name: "columns of * and GROUP BY",
		Schema: append(append([]string{}, ordSchema...),
			`ALTER TABLE cust ADD COLUMN tier int DEFAULT 0`,
			`CREATE VIEW big AS SELECT qty, id FROM ord WHERE qty > 1`),
		Seed: ordSeed, Conns: 1,
		Steps: []difftest.Step{
			difftest.Q(0, `SELECT * FROM cust ORDER BY id`),
			difftest.Q(0, `SELECT * FROM ord o JOIN cust c ON c.id = o.cust_id ORDER BY o.id`),
			difftest.Q(0, `SELECT c.*, o.qty FROM cust c LEFT JOIN ord o ON o.cust_id = c.id AND o.qty > 2 ORDER BY c.id`),
			difftest.Q(0, `SELECT *, id FROM cust ORDER BY id`),
			difftest.Q(0, `WITH t AS (SELECT qty, cust_id FROM ord) SELECT * FROM t ORDER BY qty`),
			difftest.Q(0, `SELECT * FROM (SELECT qty AS q, id FROM ord) s ORDER BY q`),
			difftest.Q(0, `SELECT * FROM big ORDER BY id`),
			difftest.Q(0, `SELECT * FROM cust WHERE false`),
			difftest.Q(0, `SELECT cust_id, count(*) FROM ord GROUP BY 1 ORDER BY 1`),
			difftest.Q(0, `SELECT count(*) FROM ord GROUP BY 2`),
			difftest.Q(0, `SELECT count(*) FROM ord GROUP BY 0`),
			difftest.Q(0, `SELECT id FROM ord ORDER BY 2`),
			difftest.Q(0, `SELECT * FROM cust ORDER BY 3`),
			difftest.Q(0, `SELECT * FROM cust ORDER BY 4`),
			difftest.Q(0, `SELECT *, 1 FROM cust ORDER BY 4`),
			difftest.Q(0, `SELECT c.*, o.qty FROM cust c JOIN ord o ON o.cust_id = c.id ORDER BY 5`),
			difftest.Q(0, `SELECT qty % 2 AS odd, count(*) FROM ord GROUP BY odd ORDER BY odd`),
			difftest.Q(0, `SELECT lower(name), count(*) FROM cust GROUP BY lower ORDER BY 1`),
			difftest.Q(0, `SELECT coalesce(o.qty, 0) AS qty, count(*) FROM cust c LEFT JOIN ord o ON o.cust_id = c.id AND o.qty > 2 GROUP BY qty ORDER BY 1`),
		},
	},
	{
		Name:   "undefined columns",
		Schema: stockSchema, Seed: stockSeed, Conns: 1,
		Steps: []difftest.Step{
			difftest.S(0, `UPDATE stock SET nope = 1`),
			difftest.S(0, `UPDATE stock SET n = 1 WHERE nope = 1`),
			difftest.S(0, `UPDATE stock SET n = nope`),
			difftest.S(0, `UPDATE stock SET sku = 'a', sku = 'b'`),
			difftest.S(0, `INSERT INTO stock (sku, nope) VALUES ('x', 1)`),
			difftest.S(0, `INSERT INTO stock VALUES ('x', nope)`),
			difftest.Q(0, `SELECT nope FROM stock`),
			difftest.Q(0, `SELECT s.nope FROM stock s`),
			difftest.Q(0, `SELECT sku FROM stock WHERE nope = 1`),
			difftest.Q(0, `SELECT sku FROM stock ORDER BY nope`),
			difftest.Q(0, `SELECT sku FROM stock WHERE n IN (SELECT nope FROM stock)`),
			difftest.Q(0, `SELECT sku FROM (SELECT sku AS s FROM stock) t`),
			difftest.Q(0, `WITH c AS (SELECT sku FROM stock) SELECT n FROM c`),
			difftest.Q(0, `SELECT typo.sku FROM stock`),
			difftest.S(0, `UPDATE stock SET n = 1 FROM LATERAL (SELECT stock.n AS m) s`),
			difftest.S(0, `DELETE FROM stock USING LATERAL (SELECT stock.n AS m) s`),
			difftest.Q(0, `SELECT typo FROM (SELECT 1, 2) s(a)`),
			difftest.Q(0, `SELECT * FROM (SELECT 1) s(a, b)`),
			difftest.Q(0, `SELECT a FROM generate_series(1, 2) AS s(a, b)`),
			difftest.Q(0, `SELECT a FROM generate_series(1, 2) WITH ORDINALITY AS s(a, o, x)`),
			difftest.Q(0, `SELECT sku FROM stock a, stock b`),
			difftest.Q(0, `SELECT sku FROM stock a, stock b, generate_series(1, 2) g`),
			difftest.Q(0, `SELECT 1 UNION SELECT 2 ORDER BY 2`),
			difftest.Q(0, `SELECT 1 UNION SELECT 2 LIMIT missing`),
			difftest.Q(0, `WITH c AS (SELECT 1 / 0) SELECT 1`),
			difftest.Q(0, `WITH c AS (SELECT 1 / 0), d AS (SELECT * FROM c) SELECT 1`),
			difftest.Q(0, `WITH c AS (SELECT 1 / 0) SELECT * FROM (WITH c AS (SELECT 1 AS n) SELECT n FROM c) x`),
			difftest.Q(0, `SELECT * FROM (SELECT 1 / 0) q(a, b)`),
			difftest.Q(0, `SELECT *`),
			difftest.Q(0, `SELECT a.sku AS sku, count(*) FROM stock a JOIN stock b ON b.sku = a.sku GROUP BY sku`),
			difftest.Q(0, `SELECT * FROM stock ORDER BY typo`),
			difftest.Q(0, `UPDATE stock AS x SET n = n WHERE sku = 'pear' RETURNING stock.*`),
			difftest.Q(0, `SELECT a.sku FROM stock a WHERE EXISTS (SELECT 1 FROM stock b WHERE sku = a.sku)`),
			difftest.Q(0, `SELECT s.sku FROM stock s JOIN stock a ON a.sku = b.sku JOIN stock b ON b.sku = s.sku`),
			difftest.Q(0, `UPDATE stock SET n = 2 WHERE sku = 'apple' RETURNING nope`),
			difftest.Q(0, `SELECT n FROM stock WHERE sku = 'apple'`),
			difftest.S(0, `DELETE FROM stock WHERE nope = 1`),
			difftest.S(0, `INSERT INTO stock VALUES ('apple', 1) ON CONFLICT (sku) DO UPDATE SET nope = 1`),
			difftest.S(0, `INSERT INTO stock VALUES ('apple', 1) ON CONFLICT (sku) DO UPDATE SET n = excluded.nope`),
			difftest.S(0, `INSERT INTO stock VALUES ('apple', 1) ON CONFLICT (nope) DO NOTHING`),
		},
	},
	{
		Name:   "column references in scope",
		Schema: ordSchema, Seed: ordSeed, Conns: 1,
		Steps: []difftest.Step{
			difftest.Q(0, `SELECT name AS who FROM cust ORDER BY who`),
			difftest.Q(0, `SELECT cust_id AS c, count(*) FROM ord GROUP BY c ORDER BY c`),
			difftest.Q(0, `SELECT c.id FROM cust c WHERE EXISTS (SELECT 1 FROM ord WHERE ord.cust_id = c.id AND qty > 2) ORDER BY c.id`),
			difftest.Q(0, `SELECT id FROM cust WHERE id IN (SELECT cust_id FROM ord WHERE qty = cust.id)`),
			difftest.Q(0, `SELECT c.id, o.total FROM cust c, LATERAL (SELECT sum(qty) AS total FROM ord WHERE ord.cust_id = c.id) o ORDER BY c.id`),
			difftest.Q(0, `WITH t AS (SELECT cust_id, qty FROM ord) SELECT cust_id FROM t WHERE qty > 1 ORDER BY cust_id`),
			difftest.Q(0, `WITH w AS (SELECT 1 AS a, 2 AS b) SELECT * FROM (WITH w AS (SELECT 3 AS c) SELECT * FROM w) s, w`),
			difftest.Q(0, `SELECT s.count FROM (SELECT count(*) FROM ord) s`),
			difftest.Q(0, `SELECT x.a FROM (SELECT id AS a FROM cust UNION SELECT cust_id FROM ord) x ORDER BY a`),
			difftest.Q(0, `SELECT id FROM cust UNION SELECT cust_id FROM ord ORDER BY id`),
			difftest.Q(0, `SELECT id AS k FROM cust UNION SELECT cust_id FROM ord ORDER BY k`),
			difftest.Q(0, `SELECT * FROM cust ORDER BY name`),
			difftest.Q(0, `SELECT c.id AS cid, count(*) FROM cust c JOIN ord o ON o.cust_id = c.id GROUP BY cid ORDER BY cid`),
			difftest.Q(0, `UPDATE cust AS x SET name = name WHERE id = 1 RETURNING x.*`),
			difftest.Q(0, `UPDATE cust AS x SET name = name WHERE id = 1 RETURNING x.id, x.name`),
			difftest.Q(0, `INSERT INTO cust AS x VALUES (3, 'c') RETURNING x.id`),
			difftest.Q(0, `DELETE FROM cust AS x WHERE id = 3 RETURNING x.id`),
			difftest.Q(0, `SELECT column1 FROM (VALUES (1), (2)) v ORDER BY column1`),
			difftest.Q(0, `VALUES (2, 'b'), (1, 'a') ORDER BY column1`),
			difftest.Q(0, `VALUES (2, 'b'), (1, 'a') ORDER BY 2`),
			difftest.Q(0, `SELECT * FROM generate_series(5, 6) WITH ORDINALITY AS s(z, a) ORDER BY z`),
			difftest.Q(0, `SELECT g FROM generate_series(1, 2) g ORDER BY g`),
			difftest.Q(0, `SELECT n FROM generate_series(1, 2) AS s(n) ORDER BY n`),
			difftest.Q(0, `SELECT a, column2 FROM (VALUES (1, 2)) v(a)`),
			difftest.Q(0, `SELECT DISTINCT ON (cust_id) cust_id, qty FROM ord ORDER BY cust_id, qty DESC`),
			difftest.Q(0, `SELECT o.* FROM ord o JOIN cust c ON c.id = o.cust_id WHERE c.name = 'b'`),
			difftest.S(0, `UPDATE ord SET qty = ord.qty + c.id FROM cust c WHERE c.id = ord.cust_id AND c.name = 'b'`),
			difftest.S(0, `DELETE FROM ord o USING cust c WHERE c.id = o.cust_id AND c.name = 'b'`),
			difftest.Q(0, `INSERT INTO cust VALUES (1, 'z') ON CONFLICT (id) DO UPDATE SET name = cust.name || excluded.name WHERE cust.id = excluded.id RETURNING id, name`),
			difftest.Q(0, `INSERT INTO ord (id, cust_id, qty) SELECT id + 100, id, 1 FROM cust ORDER BY id RETURNING id`),
			difftest.Q(0, `INSERT INTO ord VALUES (200, 1, 5) RETURNING *, qty * 2 > 9`),
			difftest.Q(0, `UPDATE ord SET qty = 6 WHERE id = 200 RETURNING id, *`),
			difftest.Q(0, `DELETE FROM ord WHERE id = 200 RETURNING *`),
		},
	},
	{
		Name:   "concurrent insert of the same key after rollback",
		Schema: stockSchema, Conns: 2,
		Steps: []difftest.Step{
			difftest.S(0, `BEGIN`),
			difftest.S(0, `INSERT INTO stock VALUES ('apple', 1)`),
			difftest.S(1, `INSERT INTO stock VALUES ('apple', 2)`),
			difftest.S(0, `ROLLBACK`),
			difftest.Q(1, `SELECT sku, n FROM stock`),
		},
	},
	{
		Name:   "insert waits on a deleted key",
		Schema: stockSchema, Seed: stockSeed, Conns: 2,
		Steps: []difftest.Step{
			difftest.S(0, `BEGIN`),
			difftest.S(0, `DELETE FROM stock WHERE sku = 'apple'`),
			difftest.S(1, `INSERT INTO stock VALUES ('apple', 2)`),
			difftest.S(0, `COMMIT`),
			difftest.Q(1, `SELECT sku, n FROM stock ORDER BY sku`),
		},
	},
	{
		Name:   "insert waits on a key being updated away",
		Schema: stockSchema, Seed: stockSeed, Conns: 2,
		Steps: []difftest.Step{
			difftest.S(0, `BEGIN`),
			difftest.S(0, `UPDATE stock SET sku = 'banana' WHERE sku = 'apple'`),
			difftest.S(1, `INSERT INTO stock VALUES ('apple', 2)`),
			difftest.S(0, `ROLLBACK`),
			difftest.Q(1, `SELECT sku, n FROM stock ORDER BY sku`),
		},
	},
	{
		Name: "immediate unique checked per statement",
		Schema: []string{
			`CREATE TABLE pos (id int PRIMARY KEY, p int UNIQUE)`,
		},
		Seed:  []string{`INSERT INTO pos VALUES (1, 1), (2, 2)`},
		Conns: 1,
		Steps: []difftest.Step{
			difftest.S(0, `UPDATE pos SET p = p + 1`),
			difftest.Q(0, `SELECT id, p FROM pos ORDER BY id`),
		},
	},
	{
		Name: "partial unique index",
		Schema: []string{
			`CREATE TABLE r (id int PRIMARY KEY, room int, active bool)`,
			`CREATE UNIQUE INDEX r_active ON r (room) WHERE active`,
		},
		Conns: 2,
		Steps: []difftest.Step{
			difftest.S(0, `INSERT INTO r VALUES (1, 1, false), (2, 1, false)`),
			difftest.S(0, `BEGIN`),
			difftest.S(0, `INSERT INTO r VALUES (3, 1, true)`),
			difftest.S(1, `INSERT INTO r VALUES (5, 1, false)`),
			difftest.S(1, `INSERT INTO r VALUES (4, 1, true)`),
			difftest.S(0, `COMMIT`),
			difftest.S(1, `UPDATE r SET active = true WHERE id = 1`),
		},
	},
	{
		Name: "unique with nulls",
		Schema: []string{
			`CREATE TABLE u (id int PRIMARY KEY, a int, b int, UNIQUE (a, b))`,
			`CREATE TABLE v (id int PRIMARY KEY, a int UNIQUE NULLS NOT DISTINCT)`,
		},
		Conns: 1,
		Steps: []difftest.Step{
			difftest.S(0, `INSERT INTO u VALUES (1, 1, NULL), (2, 1, NULL)`),
			difftest.S(0, `INSERT INTO v VALUES (1, NULL)`),
			difftest.S(0, `INSERT INTO v VALUES (2, NULL)`),
			difftest.S(0, `INSERT INTO v VALUES (2, NULL) ON CONFLICT (a) DO NOTHING`),
		},
	},
	{
		Name:   "multi-row insert fails as a whole",
		Schema: stockSchema, Seed: stockSeed, Conns: 1,
		Steps: []difftest.Step{
			difftest.S(0, `INSERT INTO stock VALUES ('kiwi', 1), ('apple', 1)`),
			difftest.Q(0, `SELECT count(*) FROM stock`),
			difftest.S(0, `INSERT INTO stock SELECT sku || '2', n FROM stock`),
			difftest.Q(0, `SELECT count(*) FROM stock`),
		},
	},
	{
		Name:   "error codes",
		Schema: []string{`CREATE TABLE e (id int PRIMARY KEY, name varchar(3) NOT NULL, n int CHECK (n > 0))`},
		Conns:  1,
		Steps: []difftest.Step{
			difftest.S(0, `INSERT INTO e VALUES (1, 'a', 1)`),
			difftest.S(0, `INSERT INTO e VALUES (2, NULL, 1)`),
			difftest.S(0, `INSERT INTO e VALUES (2, 'a', 0)`),
			difftest.S(0, `INSERT INTO e VALUES (1, 'a', 1)`),
			difftest.S(0, `INSERT INTO e VALUES (2, 'abcd', 1)`),
			difftest.Q(0, `SELECT 1 / 0`),
			difftest.Q(0, `SELECT id / (n - 1) FROM e`),
			difftest.S(0, `INSERT INTO e (name) VALUES ('a')`),
			difftest.Q(0, `SELECT * FROM nope`),
		},
	},
	{
		Name:   "affected rows of updates that change nothing",
		Schema: stockSchema, Seed: stockSeed, Conns: 1,
		Steps: []difftest.Step{
			difftest.S(0, `UPDATE stock SET n = n`),
			difftest.S(0, `UPDATE stock SET n = 1 WHERE n = 1`),
			difftest.S(0, `DELETE FROM stock WHERE false`),
			difftest.S(0, `INSERT INTO stock SELECT sku, n FROM stock WHERE false`),
		},
	},
	{
		Name:   "on conflict do nothing waits",
		Schema: stockSchema, Conns: 2,
		Steps: []difftest.Step{
			difftest.S(0, `BEGIN`),
			difftest.S(0, `INSERT INTO stock VALUES ('apple', 1)`),
			difftest.S(1, `INSERT INTO stock VALUES ('apple', 2) ON CONFLICT DO NOTHING`),
			difftest.S(0, `COMMIT`),
			difftest.Q(1, `SELECT sku, n FROM stock`),
		},
	},
	{
		Name:   "on conflict do nothing after rollback",
		Schema: stockSchema, Conns: 2,
		Steps: []difftest.Step{
			difftest.S(0, `BEGIN`),
			difftest.S(0, `INSERT INTO stock VALUES ('apple', 1)`),
			difftest.S(1, `INSERT INTO stock VALUES ('apple', 2) ON CONFLICT DO NOTHING`),
			difftest.S(0, `ROLLBACK`),
			difftest.Q(1, `SELECT sku, n FROM stock`),
		},
	},
	{
		Name:   "on conflict do update waits and updates",
		Schema: stockSchema, Conns: 2,
		Steps: []difftest.Step{
			difftest.S(0, `BEGIN`),
			difftest.S(0, `INSERT INTO stock VALUES ('apple', 1)`),
			difftest.S(1, `INSERT INTO stock VALUES ('apple', 2) ON CONFLICT (sku) DO UPDATE SET n = stock.n + EXCLUDED.n`),
			difftest.S(0, `COMMIT`),
			difftest.Q(1, `SELECT sku, n FROM stock`),
		},
	},
	{
		Name:   "on conflict do update on a locked row",
		Schema: stockSchema, Seed: stockSeed, Conns: 2,
		Steps: []difftest.Step{
			difftest.S(0, `BEGIN`),
			difftest.S(0, `UPDATE stock SET n = 10 WHERE sku = 'apple'`),
			difftest.S(1, `INSERT INTO stock VALUES ('apple', 2) ON CONFLICT (sku) DO UPDATE SET n = stock.n + EXCLUDED.n WHERE stock.n < 5`),
			difftest.S(0, `COMMIT`),
			difftest.Q(1, `SELECT sku, n FROM stock ORDER BY sku`),
		},
	},
	{
		Name:   "on conflict do update on a row being deleted",
		Schema: stockSchema, Seed: stockSeed, Conns: 2,
		Steps: []difftest.Step{
			difftest.S(0, `BEGIN`),
			difftest.S(0, `DELETE FROM stock WHERE sku = 'apple'`),
			difftest.S(1, `INSERT INTO stock VALUES ('apple', 2) ON CONFLICT (sku) DO UPDATE SET n = stock.n + EXCLUDED.n`),
			difftest.S(0, `COMMIT`),
			difftest.Q(1, `SELECT sku, n FROM stock ORDER BY sku`),
		},
	},
	{
		Name:   "on conflict do update twice in one statement",
		Schema: stockSchema, Conns: 1,
		Steps: []difftest.Step{
			difftest.S(0, `INSERT INTO stock VALUES ('apple', 1), ('apple', 2) ON CONFLICT (sku) DO UPDATE SET n = EXCLUDED.n`),
			difftest.S(0, `INSERT INTO stock VALUES ('apple', 1), ('apple', 2) ON CONFLICT DO NOTHING`),
			difftest.Q(0, `SELECT sku, n FROM stock`),
		},
	},
	{
		Name:   "on conflict within one statement",
		Schema: stockSchema, Conns: 1,
		Steps: []difftest.Step{
			difftest.S(0, `INSERT INTO stock VALUES ('apple', 1), ('apple', 2) ON CONFLICT DO NOTHING`),
			difftest.Q(0, `SELECT sku, n FROM stock`),
			difftest.S(0, `INSERT INTO stock VALUES ('pear', 1), ('pear', 2)`),
		},
	},
	{
		Name: "on conflict inference",
		Schema: []string{
			`CREATE TABLE u (id int PRIMARY KEY, email text, tenant int, deleted bool NOT NULL DEFAULT false)`,
			`CREATE UNIQUE INDEX u_email ON u (tenant, email) WHERE NOT deleted`,
			`CREATE UNIQUE INDEX u_lower ON u (lower(email))`,
		},
		Seed:  []string{`INSERT INTO u VALUES (1, 'a', 1, false)`},
		Conns: 1,
		Steps: []difftest.Step{
			difftest.S(0, `INSERT INTO u VALUES (2, 'a', 1, false) ON CONFLICT (id) DO NOTHING`),
			difftest.S(0, `INSERT INTO u VALUES (2, 'a', 1, false) ON CONFLICT (email, tenant) WHERE NOT deleted DO NOTHING`),
			difftest.S(0, `INSERT INTO u VALUES (2, 'a', 1, false) ON CONFLICT (tenant, email) DO NOTHING`),
			difftest.S(0, `INSERT INTO u VALUES (2, 'A', 2, false) ON CONFLICT (lower(email)) DO UPDATE SET tenant = 9`),
			difftest.S(0, `INSERT INTO u VALUES (2, 'b', 1, false) ON CONFLICT (email) DO NOTHING`),
			difftest.S(0, `INSERT INTO u VALUES (1, 'c', 1, false) ON CONFLICT ON CONSTRAINT u_pkey DO UPDATE SET email = 'd'`),
			difftest.Q(0, `SELECT id, email, tenant FROM u ORDER BY id`),
		},
	},
	{
		Name:   "on conflict do update returning and where",
		Schema: stockSchema, Seed: stockSeed, Conns: 1,
		Steps: []difftest.Step{
			difftest.Q(0, `INSERT INTO stock VALUES ('apple', 5) ON CONFLICT (sku) DO UPDATE SET n = stock.n + 1 WHERE stock.n > 10 RETURNING sku, n`),
			difftest.Q(0, `INSERT INTO stock VALUES ('apple', 5), ('kiwi', 2) ON CONFLICT (sku) DO UPDATE SET n = EXCLUDED.n RETURNING sku, n`),
			difftest.S(0, `INSERT INTO stock VALUES ('pear', 5) ON CONFLICT (sku) DO UPDATE SET sku = 'apple'`),
		},
	},
	{
		Name: "on conflict on a primary key that a second unique index violates",
		Schema: []string{
			`CREATE TABLE u (id int PRIMARY KEY, email text UNIQUE)`,
		},
		Seed:  []string{`INSERT INTO u VALUES (1, 'a'), (2, 'b')`},
		Conns: 1,
		Steps: []difftest.Step{
			difftest.S(0, `INSERT INTO u VALUES (3, 'a') ON CONFLICT (id) DO NOTHING`),
			difftest.S(0, `INSERT INTO u VALUES (1, 'b') ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email`),
			difftest.S(0, `INSERT INTO u VALUES (3, 'a') ON CONFLICT DO NOTHING`),
			difftest.S(0, `INSERT INTO u VALUES (3, 'a') ON CONFLICT ON CONSTRAINT u_pkey DO NOTHING`),
			difftest.S(0, `INSERT INTO u VALUES (1, 'a') ON CONFLICT ON CONSTRAINT u_email_key DO NOTHING`),
			difftest.S(0, `INSERT INTO u VALUES (3, 'a') ON CONFLICT (email, id) DO NOTHING`),
			difftest.S(0, `INSERT INTO u VALUES (3, 'a') ON CONFLICT DO UPDATE SET email = 'z'`),
			difftest.S(0, `INSERT INTO u SELECT id, email FROM u WHERE false ON CONFLICT DO UPDATE SET email = 'z'`),
			difftest.S(0, `INSERT INTO u SELECT id, email FROM u WHERE false ON CONFLICT (email, id) DO NOTHING`),
		},
	},
	{
		Name: "concurrent upsert on a second unique index",
		Schema: []string{
			`CREATE TABLE u (id int PRIMARY KEY, email text UNIQUE)`,
		},
		Conns: 2,
		Steps: []difftest.Step{
			difftest.S(0, `BEGIN`),
			difftest.S(0, `INSERT INTO u VALUES (1, 'a')`),
			difftest.S(1, `INSERT INTO u VALUES (2, 'a') ON CONFLICT (id) DO NOTHING`),
			difftest.S(0, `COMMIT`),
		},
	},
	{
		Name:   "foreign key insert takes key share on the parent",
		Schema: fkSchema, Seed: fkSeed, Conns: 2,
		Steps: []difftest.Step{
			difftest.S(0, `BEGIN`),
			difftest.S(0, `INSERT INTO child VALUES (11, 2)`),
			difftest.S(1, `UPDATE parent SET name = 'z' WHERE id = 2`),
			difftest.Q(1, `SELECT id FROM parent WHERE id = 2 FOR UPDATE NOWAIT`),
			difftest.S(1, `DELETE FROM parent WHERE id = 2`),
			difftest.S(0, `COMMIT`),
			difftest.Q(1, `SELECT id, name FROM parent ORDER BY id`),
		},
	},
	{
		Name:   "foreign key insert waits on a deleted parent",
		Schema: fkSchema, Seed: fkSeed, Conns: 2,
		Steps: []difftest.Step{
			difftest.S(0, `BEGIN`),
			difftest.S(0, `DELETE FROM parent WHERE id = 2`),
			difftest.S(1, `INSERT INTO child VALUES (11, 2)`),
			difftest.S(0, `COMMIT`),
			difftest.Q(1, `SELECT id FROM child ORDER BY id`),
		},
	},
	{
		Name:   "foreign key insert waits on a parent whose delete rolls back",
		Schema: fkSchema, Seed: fkSeed, Conns: 2,
		Steps: []difftest.Step{
			difftest.S(0, `BEGIN`),
			difftest.S(0, `DELETE FROM parent WHERE id = 2`),
			difftest.S(1, `INSERT INTO child VALUES (11, 2)`),
			difftest.S(0, `ROLLBACK`),
			difftest.Q(1, `SELECT id FROM child ORDER BY id`),
		},
	},
	{
		Name:   "foreign key insert of an uncommitted parent",
		Schema: fkSchema, Seed: fkSeed, Conns: 2,
		Steps: []difftest.Step{
			difftest.S(0, `BEGIN`),
			difftest.S(0, `INSERT INTO parent VALUES (3, 'c')`),
			difftest.S(1, `INSERT INTO child VALUES (11, 3)`),
			difftest.S(0, `COMMIT`),
			difftest.S(1, `INSERT INTO child VALUES (12, 3)`),
		},
	},
	{
		Name:   "update of a child's foreign key to an uncommitted parent",
		Schema: fkSchema, Seed: fkSeed, Conns: 2,
		Steps: []difftest.Step{
			difftest.S(0, `BEGIN`),
			difftest.S(0, `UPDATE parent SET name = 'x' WHERE id = 2`),
			difftest.S(1, `UPDATE child SET parent_id = 2 WHERE id = 10`),
			difftest.S(0, `COMMIT`),
			difftest.Q(1, `SELECT parent_id FROM child`),
		},
	},
	{
		Name:   "delete of a parent waits on a child insert",
		Schema: fkSchema, Seed: fkSeed, Conns: 2,
		Steps: []difftest.Step{
			difftest.S(0, `BEGIN`),
			difftest.S(0, `INSERT INTO child VALUES (11, 2)`),
			difftest.S(1, `DELETE FROM parent WHERE id = 2`),
			difftest.S(0, `ROLLBACK`),
			difftest.Q(1, `SELECT id FROM parent ORDER BY id`),
		},
	},
	{
		Name: "on delete cascade waits on the child",
		Schema: []string{
			`CREATE TABLE parent (id int PRIMARY KEY)`,
			`CREATE TABLE child (id int PRIMARY KEY, parent_id int REFERENCES parent (id) ON DELETE CASCADE, n int)`,
		},
		Seed:  []string{`INSERT INTO parent VALUES (1)`, `INSERT INTO child VALUES (10, 1, 0), (11, 1, 0)`},
		Conns: 2,
		Steps: []difftest.Step{
			difftest.S(0, `BEGIN`),
			difftest.S(0, `UPDATE child SET n = 1 WHERE id = 11`),
			difftest.S(1, `DELETE FROM parent WHERE id = 1`),
			difftest.S(0, `COMMIT`),
			difftest.Q(1, `SELECT count(*) FROM child`),
		},
	},
	{
		Name: "deferred foreign key checked at commit",
		Schema: []string{
			`CREATE TABLE parent (id int PRIMARY KEY)`,
			`CREATE TABLE child (id int PRIMARY KEY, parent_id int REFERENCES parent (id) DEFERRABLE INITIALLY DEFERRED)`,
		},
		Conns: 1,
		Steps: []difftest.Step{
			difftest.S(0, `BEGIN`),
			difftest.S(0, `INSERT INTO child VALUES (1, 5)`),
			difftest.S(0, `INSERT INTO parent VALUES (5)`),
			difftest.S(0, `COMMIT`),
			difftest.S(0, `BEGIN`),
			difftest.S(0, `INSERT INTO child VALUES (2, 6)`),
			difftest.S(0, `COMMIT`),
			difftest.S(0, `BEGIN`),
			difftest.S(0, `INSERT INTO child VALUES (3, 7)`),
			difftest.S(0, `SET CONSTRAINTS ALL IMMEDIATE`),
			difftest.S(0, `ROLLBACK`),
			difftest.Q(0, `SELECT id FROM child ORDER BY id`),
		},
	},
	{
		Name: "foreign key actions on update",
		Schema: []string{
			`CREATE TABLE p (id int PRIMARY KEY)`,
			`CREATE TABLE c1 (id int PRIMARY KEY, pid int REFERENCES p (id) ON UPDATE CASCADE)`,
			`CREATE TABLE c2 (id int PRIMARY KEY, pid int REFERENCES p (id) ON UPDATE SET NULL)`,
			`CREATE TABLE c3 (id int PRIMARY KEY, pid int REFERENCES p (id) ON UPDATE RESTRICT)`,
		},
		Seed:  []string{`INSERT INTO p VALUES (1), (2), (3)`, `INSERT INTO c1 VALUES (1, 1)`, `INSERT INTO c2 VALUES (1, 2)`, `INSERT INTO c3 VALUES (1, 3)`},
		Conns: 1,
		Steps: []difftest.Step{
			difftest.S(0, `UPDATE p SET id = 11 WHERE id = 1`),
			difftest.S(0, `UPDATE p SET id = 12 WHERE id = 2`),
			difftest.S(0, `UPDATE p SET id = 13 WHERE id = 3`),
			difftest.S(0, `UPDATE p SET id = 3 WHERE id = 3`),
			difftest.Q(0, `SELECT pid FROM c1`),
			difftest.Q(0, `SELECT pid IS NULL FROM c2`),
			difftest.S(0, `DELETE FROM p WHERE id = 3`),
		},
	},
	{
		Name: "self-referencing foreign keys within one statement",
		Schema: []string{
			`CREATE TABLE n (id int PRIMARY KEY, parent int REFERENCES n (id))`,
			`CREATE TABLE r (id int PRIMARY KEY, parent int REFERENCES r (id) ON DELETE RESTRICT ON UPDATE RESTRICT)`,
			`CREATE TABLE c (id int PRIMARY KEY, parent int REFERENCES c (id) ON DELETE CASCADE)`,
		},
		Conns: 1,
		Steps: []difftest.Step{
			difftest.S(0, `INSERT INTO n VALUES (2, 1), (1, NULL)`),
			difftest.S(0, `INSERT INTO n VALUES (3, 4)`),
			difftest.S(0, `INSERT INTO n SELECT id + 10, parent + 10 FROM n ORDER BY id DESC`),
			difftest.S(0, `UPDATE n SET id = id + 100, parent = parent + 100`),
			difftest.Q(0, `SELECT id, parent FROM n ORDER BY id`),
			difftest.S(0, `DELETE FROM n WHERE id IN (101, 102)`),
			difftest.S(0, `DELETE FROM n WHERE id = 101`),
			difftest.S(0, `DELETE FROM n`),
			difftest.S(0, `INSERT INTO r VALUES (2, 1), (1, NULL)`),
			difftest.S(0, `DELETE FROM r`),
			difftest.S(0, `INSERT INTO r VALUES (2, 1), (1, NULL)`),
			difftest.S(0, `UPDATE r SET id = id + 10, parent = parent + 10`),
			difftest.S(0, `INSERT INTO c VALUES (1, NULL), (2, 1), (3, 2)`),
			difftest.S(0, `DELETE FROM c WHERE id = 1`),
			difftest.Q(0, `SELECT count(*) FROM c`),
		},
	},
	{
		Name: "foreign key to another table within one statement",
		Schema: []string{
			`CREATE TABLE p (id int PRIMARY KEY)`,
			`CREATE TABLE k (id int PRIMARY KEY, pid int REFERENCES p (id))`,
		},
		Seed:  []string{`INSERT INTO p VALUES (1), (2)`, `INSERT INTO k VALUES (1, 1)`},
		Conns: 1,
		Steps: []difftest.Step{
			difftest.S(0, `UPDATE p SET id = 3 - id`),
			difftest.Q(0, `SELECT id FROM p ORDER BY id`),
		},
	},
	{
		Name: "serial values are not rolled back",
		Schema: []string{
			`CREATE TABLE s (id serial PRIMARY KEY, v text)`,
		},
		Conns: 2,
		Steps: []difftest.Step{
			difftest.S(0, `BEGIN`),
			difftest.Q(0, `INSERT INTO s (v) VALUES ('a') RETURNING id`),
			difftest.Q(1, `INSERT INTO s (v) VALUES ('b') RETURNING id`),
			difftest.S(0, `ROLLBACK`),
			difftest.Q(1, `INSERT INTO s (v) VALUES ('c') RETURNING id`),
			difftest.Q(1, `INSERT INTO s (v) VALUES ('c') ON CONFLICT DO NOTHING RETURNING id`),
			difftest.Q(1, `SELECT id, v FROM s ORDER BY id`),
		},
	},
	{
		Name:   "serial collides with an explicit id",
		Schema: []string{`CREATE TABLE s (id serial PRIMARY KEY, v text)`},
		Conns:  1,
		Steps: []difftest.Step{
			difftest.S(0, `INSERT INTO s VALUES (1, 'a')`),
			difftest.S(0, `INSERT INTO s (v) VALUES ('b')`),
			difftest.Q(0, `INSERT INTO s (v) VALUES ('c') RETURNING id`),
		},
	},
	{
		Name: "sequence options",
		Schema: []string{
			`CREATE TABLE s (id int GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 10) PRIMARY KEY, v text)`,
			`CREATE TABLE t (id bigserial PRIMARY KEY, v text)`,
			`ALTER SEQUENCE t_id_seq RESTART WITH 50`,
			`CREATE SEQUENCE q START 10 INCREMENT 5`,
			`CREATE SEQUENCE d INCREMENT -2`,
			`CREATE SEQUENCE m MINVALUE 7`,
			`CREATE SEQUENCE r START 3`,
			`ALTER SEQUENCE r INCREMENT 3 RESTART`,
			`CREATE TABLE u (id integer NOT NULL, v text)`,
			`CREATE SEQUENCE public.u_id_seq AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1`,
			`ALTER SEQUENCE public.u_id_seq OWNED BY public.u.id`,
			`ALTER TABLE ONLY public.u ALTER COLUMN id SET DEFAULT nextval('public.u_id_seq'::regclass)`,
			`CREATE TABLE w (id integer NOT NULL, v text)`,
			`ALTER TABLE public.w ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME public.w_id_seq START WITH 20 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1)`,
			`CREATE TABLE x (id int GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME x_seq START WITH 5) PRIMARY KEY, v text)`,
			`CREATE TABLE y (id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, v text)`,
			`ALTER TABLE y ALTER COLUMN id SET INCREMENT BY 4 RESTART WITH 8`,
		},
		Conns: 1,
		Steps: []difftest.Step{
			difftest.Q(0, `INSERT INTO s (v) VALUES ('a'), ('b') RETURNING id`),
			difftest.Q(0, `INSERT INTO t (v) VALUES ('a') RETURNING id`),
			difftest.Q(0, `SELECT nextval('q'), nextval('q')`),
			difftest.Q(0, `SELECT setval('q', 100), nextval('q')`),
			difftest.Q(0, `SELECT setval('q', 200, false), nextval('q'), nextval('q')`),
			difftest.Q(0, `SELECT nextval('d'), nextval('d')`),
			difftest.Q(0, `SELECT nextval('m'), nextval('r'), nextval('r')`),
			difftest.Q(0, `INSERT INTO u (v) VALUES ('a'), ('b') RETURNING id`),
			difftest.Q(0, `INSERT INTO w (v) VALUES ('a') RETURNING id`),
			difftest.Q(0, `INSERT INTO x (v) VALUES ('a') RETURNING id`),
			difftest.Q(0, `SELECT nextval('x_seq')`),
			difftest.Q(0, `INSERT INTO y (v) VALUES ('a'), ('b') RETURNING id`),
		},
	},
	{
		Name: "sequences across sessions and rollbacks",
		Schema: []string{
			`CREATE SEQUENCE q START 10 INCREMENT 5`,
		},
		Conns: 2,
		Steps: []difftest.Step{
			difftest.S(0, `BEGIN`),
			difftest.Q(0, `SELECT nextval('q')`),
			difftest.Q(1, `SELECT nextval('q')`),
			difftest.S(0, `ROLLBACK`),
			difftest.Q(0, `SELECT nextval('q')`),
		},
	},
	{
		Name: "identity modes changed by ALTER",
		Schema: []string{
			`CREATE TABLE a (id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY, v text)`,
			`ALTER TABLE a ALTER COLUMN id SET GENERATED BY DEFAULT`,
			`CREATE TABLE b (id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY, v text)`,
			`ALTER TABLE b ALTER COLUMN id DROP IDENTITY`,
			`CREATE TABLE c (id int PRIMARY KEY, n int GENERATED ALWAYS AS IDENTITY)`,
			`ALTER TABLE c DROP COLUMN n`,
			`ALTER TABLE c ADD COLUMN n int`,
		},
		Conns: 1,
		Steps: []difftest.Step{
			difftest.S(0, `INSERT INTO a (id, v) VALUES (5, 'x')`),
			difftest.Q(0, `INSERT INTO a (v) VALUES ('y') RETURNING id`),
			difftest.S(0, `INSERT INTO b (id, v) VALUES (5, 'x')`),
			difftest.S(0, `INSERT INTO b (v) VALUES ('y')`),
			difftest.S(0, `INSERT INTO c (id, n) VALUES (1, 5)`),
		},
	},
	{
		Name:   "a plain select reads its snapshot after waiting",
		Schema: stockSchema, Seed: stockSeed, Conns: 3,
		Steps: []difftest.Step{
			difftest.S(0, `BEGIN`),
			difftest.Q(0, `SELECT 1 FROM (SELECT pg_advisory_xact_lock(1)) l`),
			difftest.Q(1, `SELECT (SELECT n FROM stock WHERE sku = 'apple') FROM (SELECT pg_advisory_xact_lock(1)) l`),
			difftest.S(2, `UPDATE stock SET n = 9 WHERE sku = 'apple'`),
			difftest.S(0, `COMMIT`),
			difftest.Q(1, `SELECT n FROM stock WHERE sku = 'apple'`),
		},
	},
	{
		Name: "on conflict over an index with a repeated column",
		Schema: []string{
			`CREATE TABLE w (id int PRIMARY KEY, a int, b int)`,
			`CREATE UNIQUE INDEX w_aa ON w (a, a)`,
		},
		Seed:  []string{`INSERT INTO w VALUES (1, 1, 1)`},
		Conns: 1,
		Steps: []difftest.Step{
			difftest.S(0, `INSERT INTO w VALUES (2, 1, 2) ON CONFLICT (a, b) DO NOTHING`),
			difftest.S(0, `INSERT INTO w VALUES (2, 1, 2) ON CONFLICT (a) DO NOTHING`),
			difftest.Q(0, `SELECT count(*) FROM w`),
		},
	},
	{
		Name: "drop identity",
		Schema: []string{
			`CREATE TABLE y (id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, v text)`,
			`ALTER TABLE y ALTER COLUMN id DROP IDENTITY`,
		},
		Conns: 1,
		Steps: []difftest.Step{
			difftest.S(0, `INSERT INTO y (v) VALUES ('a')`),
		},
	},
	{
		Name:   "insert with a CTE",
		Schema: stockSchema, Seed: stockSeed, Conns: 1,
		Steps: []difftest.Step{
			difftest.S(0, `WITH s AS (SELECT sku || '2' AS sku, n FROM stock) INSERT INTO stock SELECT sku, n FROM s`),
			difftest.Q(0, `SELECT sku FROM stock ORDER BY sku`),
		},
	},
	{
		Name:   "update from with several joined rows updates once",
		Schema: ordSchema, Seed: ordSeed, Conns: 1,
		Steps: []difftest.Step{
			difftest.S(0, `UPDATE cust SET name = name || 'x' FROM ord WHERE ord.cust_id = cust.id`),
			difftest.Q(0, `SELECT id, name FROM cust ORDER BY id`),
			difftest.S(0, `DELETE FROM cust USING ord WHERE ord.cust_id = cust.id AND ord.qty > 100`),
		},
	},
	{
		Name:   "queries in a write read the rows as the statement began",
		Schema: stockSchema, Seed: []string{`INSERT INTO stock VALUES ('a', 1), ('b', 2), ('c', 3)`}, Conns: 1,
		Steps: []difftest.Step{
			difftest.S(0, `UPDATE stock SET n = n + 10 WHERE n < (SELECT max(n) FROM stock)`),
			difftest.Q(0, `SELECT sku, n FROM stock ORDER BY sku`),
			difftest.S(0, `UPDATE stock SET n = n - 10 WHERE EXISTS (SELECT 1 FROM stock s WHERE s.n > stock.n)`),
			difftest.Q(0, `SELECT sku, n FROM stock ORDER BY sku`),
			difftest.S(0, `DELETE FROM stock WHERE n > (SELECT min(n) FROM stock)`),
			difftest.Q(0, `SELECT sku, n FROM stock ORDER BY sku`),
			difftest.Q(0, `UPDATE stock SET n = (SELECT count(*) FROM stock WHERE n > 0) RETURNING sku, n`),
			difftest.S(0, `UPDATE stock SET n = 1`),
			difftest.S(0, `INSERT INTO stock VALUES ('d', 1)`),
			difftest.S(0, `UPDATE stock SET n = 0 WHERE n = (SELECT min(n) FROM stock)`),
			difftest.Q(0, `SELECT sku, n FROM stock ORDER BY sku`),
			difftest.Q(0, `UPDATE stock SET n = (SELECT max(n) FROM stock) + 1 RETURNING sku, n`),
			difftest.S(0, `DELETE FROM stock WHERE n = (SELECT max(n) FROM stock)`),
			difftest.Q(0, `SELECT count(*) FROM stock`),
		},
	},
}

func TestDiffWrites(t *testing.T) {
	for _, c := range writeCases {
		t.Run(c.Name, func(t *testing.T) {
			t.Parallel()
			difftest.Run(t, backend{}, c)
		})
	}
}
