// Package sqlcdbtx is the DBTX to give the queries sqlc generates for
// database/sql in a test, so that the goroutines sharing a transaction are
// scheduled by detest. DB and Tx have the methods of DBTX as sqlc generates
// it, and follow it when sqlc adds to it.
//
// sqlc's WithTx takes a *sql.Tx, which goroutines then use directly, so the
// package applies to code that begins its transactions through something
// the test can replace, and builds its queries on a transaction with New:
//
//	type Tx interface {
//		db.DBTX // generated by sqlc
//		Commit() error
//		Rollback() error
//	}
//
//	type Store struct {
//		begin func(ctx context.Context) (Tx, error) // db.BeginTx in production
//	}
//
//	func (s *Store) Publish(ctx context.Context) error {
//		tx, err := s.begin(ctx)
//		...
//		q := db.New(tx)
//		...
//	}
//
// and in the test:
//
//	sqlDB, store := s.DB("app", postgres.New())
//	pool := sqlcdbtx.New(sqlDB)
//	st := &Store{begin: func(ctx context.Context) (Tx, error) { return pool.BeginTx(ctx, nil) }}
//
// Code that takes WithTx's *sql.Tx runs on the *sql.DB all the same. A
// goroutine that uses a transaction another process began then runs each
// statement at once, without yielding, and a statement of it that would
// wait for a lock fails as unsupported, as the README describes. Through
// the pool, each operation of such a goroutine waits for the transaction's
// connection before it enters database/sql, so its statements yield, wait
// for locks and take part in deadlocks as any process's do, and the order
// of the goroutines is explored.
//
// A commit or a rollback by a goroutine other than the one that began the
// transaction is still refused. A statement prepared on the transaction
// runs without the pool.
package sqlcdbtx

import (
	"context"
	"database/sql"

	"github.com/k1LoW/detest/internal/seam"
)

// DB is a DBTX over a *sql.DB that begins transactions whose operations go
// through it.
type DB struct{ db *sql.DB }

// New returns the DB to begin the code's transactions on.
func New(db *sql.DB) *DB { return &DB{db: db} }

func (d *DB) ExecContext(ctx context.Context, query string, args ...any) (sql.Result, error) {
	return d.db.ExecContext(ctx, query, args...)
}

func (d *DB) PrepareContext(ctx context.Context, query string) (*sql.Stmt, error) {
	return d.db.PrepareContext(ctx, query)
}

func (d *DB) QueryContext(ctx context.Context, query string, args ...any) (*sql.Rows, error) {
	return d.db.QueryContext(ctx, query, args...)
}

func (d *DB) QueryRowContext(ctx context.Context, query string, args ...any) *sql.Row {
	return d.db.QueryRowContext(ctx, query, args...)
}

// BeginTx begins a transaction on the *sql.DB.
func (d *DB) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	ctx, slot := seam.WithSlot(ctx)
	tx, err := d.db.BeginTx(ctx, opts)
	if err != nil {
		return nil, err
	}
	return &Tx{tx: tx, seam: slot}, nil
}

// Tx is a transaction BeginTx began. Each of its operations waits for the
// transaction's connection before it calls the *sql.Tx.
type Tx struct {
	tx   *sql.Tx
	seam *seam.Slot
}

func (t *Tx) ExecContext(ctx context.Context, query string, args ...any) (sql.Result, error) {
	release, err := t.seam.Enter("exec", query, args...)
	if err != nil {
		return nil, err
	}
	defer release()
	return t.tx.ExecContext(ctx, query, args...)
}

func (t *Tx) PrepareContext(ctx context.Context, query string) (*sql.Stmt, error) {
	release, err := t.seam.Enter("prepare", query)
	if err != nil {
		return nil, err
	}
	defer release()
	return t.tx.PrepareContext(ctx, query)
}

// QueryContext gives the connection back when it returns, but the driver
// keeps it until the rows are closed.
func (t *Tx) QueryContext(ctx context.Context, query string, args ...any) (*sql.Rows, error) {
	release, err := t.seam.Enter("query", query, args...)
	if err != nil {
		return nil, err
	}
	defer release()
	return t.tx.QueryContext(ctx, query, args...)
}

// QueryRowContext is QueryContext for one row. A *sql.Row cannot carry an
// error of the pool's, so when the run is over it calls the *sql.Tx all the
// same, and the driver returns the end of the run.
func (t *Tx) QueryRowContext(ctx context.Context, query string, args ...any) *sql.Row {
	release, err := t.seam.Enter("query", query, args...)
	if err == nil {
		defer release()
	}
	return t.tx.QueryRowContext(ctx, query, args...)
}

func (t *Tx) Commit() error {
	release, err := t.seam.Enter("commit", "")
	if err != nil {
		return err
	}
	defer release()
	return t.tx.Commit()
}

func (t *Tx) Rollback() error {
	release, err := t.seam.Enter("rollback", "")
	if err != nil {
		return err
	}
	defer release()
	return t.tx.Rollback()
}
